[package]
name = "chronometric_examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
#
deep_causality_num = { workspace = true, features = ["default"] }
deep_causality_algebra = { workspace = true, features = ["default"] }
deep_causality_core = { workspace = true, features = ["default"] }
deep_causality_physics = { workspace = true, features = ["default", "os-random"] }
deep_causality_file = { workspace = true }

[[example]]
name = "gm_recovery"
path = "gm_recovery/main.rs"

[lints]
workspace = true
