# https://docs.codecov.com/docs/common-recipe-list
comment:
  require_changes: true

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - "docs/"
  - "end_to_end_tutorials/"
  - "examples/"  # ignore folders and all its contents
  - "lean/"
  - "openspec/"
  - "tsc/"
  - "yanked/"  # ignore folders and all its contents