version = 1

# Reuse annotations file.
#
# This file controls how reuse-tool finds copyright and license notices within
# source files.
#
# See https://reuse.software and https://github.com/fsfe/reuse-tool for more
# details.

[[annotations]]
path = "**"
SPDX-FileCopyrightText = " The DeepCausality Authors and Contributors. All Rights Reserved."
SPDX-License-Identifier = "MIT"