/-
SPDX-License-Identifier: MIT
Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.

Haft — the reified free Arrow (`ArrowTerm`) and its interpretation.

Rust source: `deep_causality_haft/src/arrow/arrow_term.rs` (`ArrowCore`, `ArrowVal`, `ArrowCore::interpret`).

Textbook definition. Given a strong category (an Arrow, in the sense of Hughes) the terms freely
generated by a set `G` of generators under the operations `id`, `compose` (`>>>`), `first`,
`second`, `split` (`***`), `fanout` (`&&&`) form the **free arrow** over `G`. As with any free /
initial construction, it carries a universal property: an interpretation of the *generators* into a
target extends **uniquely** to an arrow-homomorphism on the whole term. This is the
initial-algebra-of-a-signature pattern — a free term algebra whose universal map is defined by
structural recursion (John Hughes, "Generalising Monads to Arrows," *Sci. Comput. Program.*
37(1–3), 2000, for the arrow operations; Steve Awodey, *Category Theory* 2nd ed., §5, and
J. Goguen, J. Thatcher, E. Wagner, J. Wright, "Initial Algebra Semantics and Continuous Algebras,"
*J. ACM* 24(1), 1977, for free objects / initial-algebra semantics; John C. Reynolds, "Definitional
Interpreters for Higher-Order Programming Languages," ACM Annual Conf. 1972, for the first-order
"erased core" encoding).

This file proves the two facts the Rust reification rests on:
  * `interpret_sound` — interpretation is a homomorphism: the interpreter commutes with every
    combinator (`compose` becomes sequencing, `split`/`first`/`second` act componentwise, `fanout`
    copies). This is the precise content of "interpreting a term equals composing its combinators."
  * `free` — interpretation is **determined by the generators**: two generator-interpretations that
    agree everywhere induce equal interpretations on every term (the free arrow's universal
    property, proved by structural induction).

DEVIATION NOTES.
  1. Rust has no GADTs, so the object (input/output) types are **erased** in the storable core;
     interpretation therefore runs over one uniform value universe `ArrowVal` — a binary tree whose
     `pair` node models the monoidal product the strength combinators act on — rather than over
     typed objects. Static well-typedness is recovered on the Rust side by the `ArrowTerm<In,Out,G>`
     façade (not modelled here; it adds no equations).
  2. Generators are interpreted as **leaf endomorphisms** `φ : G → V → V` (a monomorphic target),
     which suffices to state and prove the free-extension property; a fully object-indexed target is
     not needed for these laws.
  3. A combinator applied to a value of the wrong shape (e.g. `first` on a `leaf`) passes the value
     through unchanged — unreachable for a term fed its declared input shape, matching the Rust
     façade; it only makes `interpret` total.

This file is self-contained (no imports) so it typechecks standalone with bare `lean`.

Rust witness: `deep_causality_haft/tests/formalization_lean/arrow_term_tests.rs`.

Imports: keep to the exact minimum. Every Mathlib import pulls its whole transitive closure into
the build, so import the narrowest module that still type-checks -- `Mathlib.Analysis.Quaternion`
once reached 8,639 of Mathlib's 9,450 modules to supply four algebraic laws. Mirror any new import
into `cache_roots` in `//MODULE.bazel`: that list tree-shakes the Mathlib olean download to those
roots plus their closure, so a module absent from it is never fetched and the build fails on it.
-/

namespace DeepCausalityFormal.Haft.ArrowTerm

/-- The erased core: the free arrow over a generator set `G`, as first-order data. Mirrors the Rust
    `ArrowCore<G>` enum — including the choice generators `left`/`right`/`choice`/`fanin` of the
    `⊕` fragment (Stage 2b; Hughes 2000 §5). -/
inductive ArrowCore (G : Type) : Type where
  | id
  | gen (g : G)
  | compose (f h : ArrowCore G)
  | first (f : ArrowCore G)
  | second (f : ArrowCore G)
  | split (f h : ArrowCore G)
  | fanout (f h : ArrowCore G)
  | left (f : ArrowCore G)
  | right (f : ArrowCore G)
  | choice (f h : ArrowCore G)
  | fanin (f h : ArrowCore G)

/-- The value universe interpreted terms flow through — a binary tree with payload leaves, product
    (`pair`) nodes, and the sum (`inl`/`inr`) nodes the choice generators route on. Mirrors the
    Rust `ArrowVal<V>`. -/
inductive ArrowVal (V : Type) : Type where
  | leaf (v : V)
  | pair (a b : ArrowVal V)
  | inl (a : ArrowVal V)
  | inr (b : ArrowVal V)

/-- The interpreter: extend a generator interpretation `φ` homomorphically over the whole term.
    Mirrors `ArrowCore::interpret` line for line — the choice generators route on the sum node,
    with `fanin` UNWRAPPING the injection (the coproduct elimination). A combinator applied to a
    value of the wrong shape passes it through (deviation note 3). -/
def interpret {G V : Type} (φ : G → V → V) : ArrowCore G → ArrowVal V → ArrowVal V
  | .id,          x           => x
  | .gen g,       .leaf v     => .leaf (φ g v)
  | .gen _,       .pair a b   => .pair a b
  | .gen _,       .inl a      => .inl a
  | .gen _,       .inr b      => .inr b
  | .compose f h, x           => interpret φ h (interpret φ f x)
  | .first _,     .leaf v     => .leaf v
  | .first f,     .pair a b   => .pair (interpret φ f a) b
  | .first _,     .inl a      => .inl a
  | .first _,     .inr b      => .inr b
  | .second _,    .leaf v     => .leaf v
  | .second f,    .pair a b   => .pair a (interpret φ f b)
  | .second _,    .inl a      => .inl a
  | .second _,    .inr b      => .inr b
  | .split _ _,   .leaf v     => .leaf v
  | .split f h,   .pair a b   => .pair (interpret φ f a) (interpret φ h b)
  | .split _ _,   .inl a      => .inl a
  | .split _ _,   .inr b      => .inr b
  | .fanout f h,  x           => .pair (interpret φ f x) (interpret φ h x)
  | .left f,      .inl a      => .inl (interpret φ f a)
  | .left _,      .leaf v     => .leaf v
  | .left _,      .pair a b   => .pair a b
  | .left _,      .inr b      => .inr b
  | .right f,     .inr b      => .inr (interpret φ f b)
  | .right _,     .leaf v     => .leaf v
  | .right _,     .pair a b   => .pair a b
  | .right _,     .inl a      => .inl a
  | .choice f _,  .inl a      => .inl (interpret φ f a)
  | .choice _ h,  .inr b      => .inr (interpret φ h b)
  | .choice _ _,  .leaf v     => .leaf v
  | .choice _ _,  .pair a b   => .pair a b
  | .fanin f _,   .inl a      => interpret φ f a
  | .fanin _ h,   .inr b      => interpret φ h b
  | .fanin _ _,   .leaf v     => .leaf v
  | .fanin _ _,   .pair a b   => .pair a b

variable {G V : Type}

/-- Interpretation is a homomorphism: it commutes with every combinator. `compose` becomes
    sequencing, `first`/`second`/`split` act componentwise on a `pair`, `fanout` copies — the exact
    content of "interpreting a term equals composing its combinators." Each equation is definitional.

    THEOREM_MAP: `haft.arrow_term.interpret_sound` -/
theorem interpret_sound (φ : G → V → V) :
    (∀ x, interpret φ .id x = x)
    ∧ (∀ f h x, interpret φ (.compose f h) x = interpret φ h (interpret φ f x))
    ∧ (∀ f a b, interpret φ (.first f) (.pair a b) = .pair (interpret φ f a) b)
    ∧ (∀ f a b, interpret φ (.second f) (.pair a b) = .pair a (interpret φ f b))
    ∧ (∀ f h a b,
        interpret φ (.split f h) (.pair a b) = .pair (interpret φ f a) (interpret φ h b))
    ∧ (∀ f h x, interpret φ (.fanout f h) x = .pair (interpret φ f x) (interpret φ h x)) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;> intros <;> rfl

/-- Interpreting the choice generators agrees with the eager ArrowChoice combinators
    (`Haft/ArrowChoice.lean`): `left`/`right`/`choice` route on the sum node component-wise, and
    `fanin` eliminates it — each equation is definitional, extending `interpret_sound` to the
    `⊕`-enlarged generator set.

    THEOREM_MAP: `haft.arrow_term.choice_interpret_sound` -/
theorem choice_interpret_sound (φ : G → V → V) :
    (∀ f a, interpret φ (.left f) (.inl a) = .inl (interpret φ f a))
    ∧ (∀ f b, interpret φ (.left f) (.inr b) = .inr b)
    ∧ (∀ f b, interpret φ (.right f) (.inr b) = .inr (interpret φ f b))
    ∧ (∀ f a, interpret φ (.right f) (.inl a) = .inl a)
    ∧ (∀ f h a, interpret φ (.choice f h) (.inl a) = .inl (interpret φ f a))
    ∧ (∀ f h b, interpret φ (.choice f h) (.inr b) = .inr (interpret φ h b))
    ∧ (∀ f h a, interpret φ (.fanin f h) (.inl a) = interpret φ f a)
    ∧ (∀ f h b, interpret φ (.fanin f h) (.inr b) = interpret φ h b) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> intros <;> rfl

/-- The free arrow's universal property: interpretation is **determined by the generators**. If two
    generator-interpretations agree everywhere, they induce equal interpretations on every term —
    including every term of the `⊕`-enlarged set. Proved by structural induction on the term.

    THEOREM_MAP: `haft.arrow_term.free` -/
theorem free (φ ψ : G → V → V) (hgen : ∀ g v, φ g v = ψ g v) :
    ∀ (t : ArrowCore G) (x : ArrowVal V), interpret φ t x = interpret ψ t x := by
  intro t
  induction t with
  | id => intro x; rfl
  | gen g =>
      intro x
      cases x with
      | leaf v => show ArrowVal.leaf (φ g v) = ArrowVal.leaf (ψ g v); rw [hgen g v]
      | pair a b => rfl
      | inl a => rfl
      | inr b => rfl
  | compose f h ihf ihh =>
      intro x
      show interpret φ h (interpret φ f x) = interpret ψ h (interpret ψ f x)
      rw [ihf x, ihh (interpret ψ f x)]
  | first f ihf =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b =>
          show ArrowVal.pair (interpret φ f a) b = ArrowVal.pair (interpret ψ f a) b
          rw [ihf a]
      | inl a => rfl
      | inr b => rfl
  | second f ihf =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b =>
          show ArrowVal.pair a (interpret φ f b) = ArrowVal.pair a (interpret ψ f b)
          rw [ihf b]
      | inl a => rfl
      | inr b => rfl
  | split f h ihf ihh =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b =>
          show ArrowVal.pair (interpret φ f a) (interpret φ h b)
              = ArrowVal.pair (interpret ψ f a) (interpret ψ h b)
          rw [ihf a, ihh b]
      | inl a => rfl
      | inr b => rfl
  | fanout f h ihf ihh =>
      intro x
      show ArrowVal.pair (interpret φ f x) (interpret φ h x)
          = ArrowVal.pair (interpret ψ f x) (interpret ψ h x)
      rw [ihf x, ihh x]
  | left f ihf =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b => rfl
      | inl a =>
          show ArrowVal.inl (interpret φ f a) = ArrowVal.inl (interpret ψ f a)
          rw [ihf a]
      | inr b => rfl
  | right f ihf =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b => rfl
      | inl a => rfl
      | inr b =>
          show ArrowVal.inr (interpret φ f b) = ArrowVal.inr (interpret ψ f b)
          rw [ihf b]
  | choice f h ihf ihh =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b => rfl
      | inl a =>
          show ArrowVal.inl (interpret φ f a) = ArrowVal.inl (interpret ψ f a)
          rw [ihf a]
      | inr b =>
          show ArrowVal.inr (interpret φ h b) = ArrowVal.inr (interpret ψ h b)
          rw [ihh b]
  | fanin f h ihf ihh =>
      intro x
      cases x with
      | leaf v => rfl
      | pair a b => rfl
      | inl a => exact ihf a
      | inr b => exact ihh b

/-- The universal property, restated for the choice fragment: two generator-interpretations that
    agree induce equal interpretations on every `left`/`right`/`choice`/`fanin` term — the freeness
    of the `⊕`-enlarged free arrow (a direct corollary of `free`, stated with its own id so the
    enlargement is separately pinned).

    THEOREM_MAP: `haft.arrow_term.choice_free` -/
theorem choice_free (φ ψ : G → V → V) (hgen : ∀ g v, φ g v = ψ g v) (f h : ArrowCore G) :
    (∀ x, interpret φ (.left f) x = interpret ψ (.left f) x)
    ∧ (∀ x, interpret φ (.right f) x = interpret ψ (.right f) x)
    ∧ (∀ x, interpret φ (.choice f h) x = interpret ψ (.choice f h) x)
    ∧ (∀ x, interpret φ (.fanin f h) x = interpret ψ (.fanin f h) x) :=
  ⟨fun x => free φ ψ hgen (.left f) x,
   fun x => free φ ψ hgen (.right f) x,
   fun x => free φ ψ hgen (.choice f h) x,
   fun x => free φ ψ hgen (.fanin f h) x⟩

end DeepCausalityFormal.Haft.ArrowTerm
