// SPDX-License-Identifier: MIT
// Copyright (c) "2025" . The DeepCausality Authors and Contributors. All Rights Reserved.

use crate::traits::log_append::LogAppend;
use crate::{CausalEffectLog, CausalityError, EffectValue};
use deep_causality_haft::{Applicative, Functor, HKT, HKT3, Monad, Placeholder};

mod constructors;
mod display;
mod explain;
mod predicates;

#[derive(Debug, PartialEq, Clone)]
pub struct CausalPropagatingEffect<Value, Error, Log> {
    pub value: Value,
    pub error: Option<Error>,
    pub logs: Log,
}

impl<Value, Error, Log> CausalPropagatingEffect<Value, Error, Log>
where
    Error: Clone,
    Log: Clone,
{
    /// Enables fluent, chainable monadic operations on a `CausalPropagatingEffect`.
    ///
    /// This method takes ownership of the current effect and a function that transforms
    /// the inner value. It automatically handles error short-circuiting and log aggregation.
    ///
    /// # Arguments
    /// * `f`: A function that takes the current inner `Value` and returns a new
    ///   `CausalPropagatingEffect` with a potentially different inner `NewValue`.
    ///
    /// # Returns
    /// A new `CausalPropagatingEffect` that is the result of the sequenced operation.
    ///
    /// # Log Provenance
    /// This `bind` method is central to ensuring log provenance across monadic operations.
    /// It guarantees that the log history is always preserved and appended to, never overwritten.
    ///
    /// - If the current effect contains an error, its logs are passed through unchanged
    ///   to the returned effect, and the provided function `f` is not executed.
    /// - If there is no error, `bind` first captures the accumulated logs from the current effect.
    ///   It then executes the provided function `f`, which returns a new `CausalPropagatingEffect`
    ///   containing logs specific to its operation.
    /// - Finally, `bind` extends the accumulated logs from the current effect with the logs
    ///   generated by `f`, ensuring a complete and ordered history is carried forward.
    pub fn bind<F, NewValue>(self, f: F) -> CausalPropagatingEffect<NewValue, Error, Log>
    where
        F: FnOnce(Value) -> CausalPropagatingEffect<NewValue, Error, Log>,
        NewValue: Default,
        Log: Default + Clone + LogAppend,
    {
        if let Some(error) = self.error {
            return CausalPropagatingEffect {
                value: NewValue::default(),
                error: Some(error),
                logs: self.logs,
            };
        }

        let mut next_effect = f(self.value);
        let mut combined_logs = self.logs;
        combined_logs.append(&mut next_effect.logs);
        next_effect.logs = combined_logs;
        next_effect
    }
}

pub type PropagatingEffect = CausalPropagatingEffect<EffectValue, CausalityError, CausalEffectLog>;

pub struct PropagatingEffectWitness<E, L>(Placeholder, E, L);

impl<E, L> HKT for PropagatingEffectWitness<E, L> {
    type Type<T> = CausalPropagatingEffect<T, E, L>;
}

impl<E, L> HKT3<E, L> for PropagatingEffectWitness<E, L> {
    type Type<T> = CausalPropagatingEffect<T, E, L>;
}

impl<E, L> Functor<PropagatingEffectWitness<E, L>> for PropagatingEffectWitness<E, L>
where
    E: 'static,
    L: 'static,
{
    fn fmap<A, B, Func>(
        m_a: <PropagatingEffectWitness<E, L> as HKT>::Type<A>,
        f: Func,
    ) -> <PropagatingEffectWitness<E, L> as HKT>::Type<B>
    where
        Func: FnOnce(A) -> B,
    {
        CausalPropagatingEffect {
            value: f(m_a.value),
            error: m_a.error,
            logs: m_a.logs,
        }
    }
}

impl<E> Applicative<PropagatingEffectWitness<E, CausalEffectLog>>
    for PropagatingEffectWitness<E, CausalEffectLog>
where
    E: 'static + Clone,
{
    fn pure<T>(value: T) -> <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<T> {
        CausalPropagatingEffect {
            value,
            error: None,
            logs: CausalEffectLog::new(),
        }
    }

    fn apply<A, B, Func>(
        mut f_ab: <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<Func>,
        mut f_a: <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<A>,
    ) -> <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<B>
    where
        Func: FnMut(A) -> B,
        A: Clone,
    {
        if f_ab.error.is_some() {
            return CausalPropagatingEffect {
                value: (f_ab.value)(f_a.value),
                error: f_ab.error,
                logs: f_ab.logs,
            };
        }
        if f_a.error.is_some() {
            return CausalPropagatingEffect {
                value: (f_ab.value)(f_a.value),
                error: f_a.error,
                logs: f_a.logs,
            };
        }

        let mut combined_logs = f_ab.logs;
        combined_logs.append(&mut f_a.logs);

        CausalPropagatingEffect {
            value: (f_ab.value)(f_a.value),
            error: None,
            logs: combined_logs,
        }
    }
}

impl<E> Monad<PropagatingEffectWitness<E, CausalEffectLog>>
    for PropagatingEffectWitness<E, CausalEffectLog>
where
    E: 'static + Clone,
{
    fn bind<A, B, Func>(
        m_a: <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<A>,
        f: Func,
    ) -> <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<B>
    where
        Func: FnOnce(A) -> <PropagatingEffectWitness<E, CausalEffectLog> as HKT>::Type<B>,
    {
        if m_a.error.is_some() {
            return CausalPropagatingEffect {
                value: f(m_a.value).value,
                error: m_a.error,
                logs: m_a.logs,
            };
        }
        let mut next_effect = f(m_a.value);
        let mut combined_logs = m_a.logs;
        combined_logs.append(&mut next_effect.logs);
        next_effect.logs = combined_logs;
        next_effect
    }
}
