// SPDX-License-Identifier: MIT
// Copyright (c) "2025" . The DeepCausality Authors and Contributors. All Rights Reserved.

use crate::traits::log_append::LogAppend;
use crate::{CausalEffectLog, CausalityError, EffectValue};
use deep_causality_haft::Placeholder;

mod constructors;
mod display;
mod explain;
mod hkt;
mod predicates;

#[derive(Debug, PartialEq, Clone)]
pub struct CausalPropagatingEffect<Value, Error, Log> {
    pub value: Value,
    pub error: Option<Error>,
    pub logs: Log,
}

impl<Value, Error, Log> CausalPropagatingEffect<Value, Error, Log>
where
    Error: Clone,
    Log: Clone,
{
    /// Enables fluent, chainable monadic operations on a `CausalPropagatingEffect`.
    ///
    /// This method takes ownership of the current effect and a function that transforms
    /// the inner value. It automatically handles error short-circuiting and log aggregation.
    ///
    /// # Arguments
    /// * `f`: A function that takes the current inner `Value` and returns a new
    ///   `CausalPropagatingEffect` with a potentially different inner `NewValue`.
    ///
    /// # Returns
    /// A new `CausalPropagatingEffect` that is the result of the sequenced operation.
    ///
    /// # Log Provenance
    /// This `bind` method is central to ensuring log provenance across monadic operations.
    /// It guarantees that the log history is always preserved and appended to, never overwritten.
    ///
    /// - If the current effect contains an error, its logs are passed through unchanged
    ///   to the returned effect, and the provided function `f` is not executed.
    /// - If there is no error, `bind` first captures the accumulated logs from the current effect.
    ///   It then executes the provided function `f`, which returns a new `CausalPropagatingEffect`
    ///   containing logs specific to its operation.
    /// - Finally, `bind` extends the accumulated logs from the current effect with the logs
    ///   generated by `f`, ensuring a complete and ordered history is carried forward.
    pub fn bind<F, NewValue>(self, f: F) -> CausalPropagatingEffect<NewValue, Error, Log>
    where
        F: FnOnce(Value) -> CausalPropagatingEffect<NewValue, Error, Log>,
        NewValue: Default,
        Log: Default + Clone + LogAppend,
    {
        if let Some(error) = self.error {
            return CausalPropagatingEffect {
                value: NewValue::default(),
                error: Some(error),
                logs: self.logs,
            };
        }

        let mut next_effect = f(self.value);
        let mut combined_logs = self.logs;
        combined_logs.append(&mut next_effect.logs);
        next_effect.logs = combined_logs;
        next_effect
    }
}

pub type PropagatingEffect = CausalPropagatingEffect<EffectValue, CausalityError, CausalEffectLog>;

pub struct PropagatingEffectWitness<E, L>(Placeholder, E, L);
