[package]
name = "example_effect_ethos"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[dependencies]
deep_causality = { path = "../../deep_causality" }
