/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
 */

//! # Turbulence predictability in avionics: the forecast horizon of a chaotic flow
//!
//! Avionics must reckon with turbulence (atmospheric convection, thermals, storm cells, wake and
//! clear-air turbulence) for structural loads, ride quality, and control. Turbulent flow is
//! chaotic, so any forecast of it has a hard predictability horizon: past some lead time the
//! prediction is worthless however good the model, because the flow amplifies the smallest error
//! exponentially. This example locates that horizon and shows what moves it.
//!
//! The testbed is the Lorenz system, Saltzman and Lorenz's three-mode truncation of
//! Rayleigh-Bénard convection. It is the original model of atmospheric convective turbulence and
//! the birthplace of chaos theory: small enough to run in a few lines, yet exhibiting the property
//! that caps every turbulence forecast, exponential error growth (leading Lyapunov exponent
//! `λ ≈ 0.906`).
//!
//! The avionics-relevant result is that the horizon is set by the smallest error in the
//! computation, and the irreducible floor is floating-point roundoff. How far ahead a chaotic flow
//! can be trusted is therefore, in the end, a question of arithmetic precision: `Float106` roughly
//! doubles the trustworthy horizon that `f64` can reach.
//!
//! The example rests on three DeepCausality pillars and little else. The integration operator
//! `Rk4` marches the flow; the model is written once over `Scalar`, so precision is a type
//! parameter (`f32` / `f64` / `Float106`); and the causal monad `PropagatingEffect` sequences
//! simulate then analyse, short-circuiting if a trajectory leaves the finite range.

mod model;
mod print_utils;

use deep_causality_core::{CausalFlow, CausalityError, CausalityErrorEnum, PropagatingEffect};
use deep_causality_num::Float106;
use model::{ConvectionParams, Forecasts, Report, Row, Vec3};

fn main() {
    println!(
        "=== Turbulence predictability: the forecast horizon of a chaotic convective flow ===\n"
    );

    // ── Study parameters. This example carries no `constants.rs`, so each value is justified here.
    //
    // `dt`: the Rk4 step. It is the same at every precision, which is the whole design of the
    // measurement: an identical scheme at an identical step makes the truncation error common to
    // the three runs, so it cancels in their difference and the distance that remains is roundoff
    // growth alone. Its size therefore sets accuracy, not the reported horizons.
    //
    // `ic`: the initial state. Each component is exactly representable in f32, f64 and Float106,
    // so all three forecasts start from the same point and every separation is generated by the
    // march rather than by the conversion of the initial condition.
    //
    // `sample_dt`: snapshot spacing, two samples per time unit. Horizons are read off the samples,
    // so this is also the quantum the reported horizon is resolved to (hence `t ≈ 21.5`, `44.5`).
    //
    // `samples`: 120 snapshots at 0.5 is `T = 60`. Long enough that f32 and f64 both cross the
    // threshold inside the run; Float106's predicted crossing near `t ≈ 81` lies beyond it, which
    // is why the report states that horizon from the law instead of measuring it.
    let params = ConvectionParams::default();
    let dt = 0.005_f64;
    let ic = [1.0_f64, 1.0, 1.0];
    let sample_dt = 0.5_f64;
    let samples = 120usize;
    let steps_per_sample = (sample_dt / dt) as usize; // 100 steps between snapshots

    // The workflow is a causal-monad chain: forecast at three precisions, then (only if every
    // trajectory stayed finite) analyse the divergence. A blow-up short-circuits the error channel.
    CausalFlow::effect()
        .next(move |_| simulate(&params, dt, ic, samples, steps_per_sample).into())
        .next(move |sims| analyse(sims, sample_dt).into())
        .run(
            |report| print_utils::print_report(&report),
            |err| eprintln!("Turbulence-forecast pipeline failed: {err:?}"),
        );
}

/// Stage 1: forecast the same flow at f32, f64, and Float106, then lift the two low-precision
/// trajectories into Float106 so every comparison happens in the widest type.
fn simulate(
    p: &ConvectionParams,
    dt: f64,
    ic: [f64; 3],
    samples: usize,
    steps_per_sample: usize,
) -> PropagatingEffect<Forecasts> {
    let f32_traj = model::run::<f32>(p, dt, ic, samples, steps_per_sample);
    let f64_traj = model::run::<f64>(p, dt, ic, samples, steps_per_sample);
    let ref_traj = model::run::<Float106>(p, dt, ic, samples, steps_per_sample);

    let f32_106: Vec<Vec3<Float106>> = f32_traj.into_iter().map(model::f32_to_106).collect();
    let f64_106: Vec<Vec3<Float106>> = f64_traj.into_iter().map(model::f64_to_106).collect();

    if !model::all_finite(&ref_traj) {
        return fail("a trajectory diverged to a non-finite state");
    }

    PropagatingEffect::pure(Forecasts {
        f32_106,
        f64_106,
        ref_106: ref_traj,
    })
}

/// Stage 2: measure each precision's forecast horizon (where it parts from the Float106 trajectory
/// by more than one state-space unit) and tabulate the divergence over time.
fn analyse(s: Forecasts, sample_dt: f64) -> PropagatingEffect<Report> {
    // The separation at which a forecast is declared lost: one state-space unit. This is the `L` of
    // the horizon law `t ≈ ln(L/ε)/λ` that `Report::horizon_law` evaluates, and it sets every
    // horizon this example reports. The value is conservative against the flow it measures: the
    // attractor is tens of units across, so a forecast is called dead while it is still a plausible
    // state on the right attractor. Declaring the loss at attractor scale instead would raise all
    // three horizons by `ln(L)/λ`, about 2.5 time units per decade, and leave their order alone.
    let threshold = 1.0;
    let h_f32 = model::forecast_horizon(&s.f32_106, &s.ref_106, sample_dt, threshold);
    let h_f64 = model::forecast_horizon(&s.f64_106, &s.ref_106, sample_dt, threshold);

    let mut rows = Vec::new();
    let mut t = 5.0_f64;
    while t <= 55.0 {
        let k = (t / sample_dt) as usize;
        if k < s.ref_106.len() {
            rows.push(Row {
                t,
                d_f32: format!("{:.2e}", model::distance(s.f32_106[k], s.ref_106[k])),
                d_f64: format!("{:.2e}", model::distance(s.f64_106[k], s.ref_106[k])),
            });
        }
        t += 5.0;
    }

    PropagatingEffect::pure(Report { h_f32, h_f64, rows })
}

fn fail<T: Default + Clone + std::fmt::Debug>(msg: &str) -> PropagatingEffect<T> {
    PropagatingEffect::from_error(CausalityError::new(CausalityErrorEnum::Custom(msg.into())))
}
