load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_library", "rust_test_suite")

rust_library(
    name = "deep_causality_metric",
    srcs = glob([
        "src/**/*.rs",
    ]),
    crate_features = [
        "alloc",
        "std",
    ],
    crate_root = "src/lib.rs",
    tags = [
        "math",
        "metric",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)

rust_doc(
    name = "doc",
    crate = ":deep_causality_metric",
    crate_features = [
        "alloc",
        "std",
    ],
    tags = ["doc"],
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    crate = ":deep_causality_metric",
    crate_features = [
        "alloc",
        "std",
    ],
    tags = ["doc-test"],
    visibility = ["//visibility:public"],
)

rust_test_suite(
    name = "conventions",
    srcs = glob([
        "tests/conventions/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_metric",
    ],
)

rust_test_suite(
    name = "errors",
    srcs = glob([
        "tests/errors/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_metric",
    ],
)

rust_test_suite(
    name = "types",
    srcs = glob([
        "tests/types/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_metric",
    ],
)
