load("@rules_rust//rust:defs.bzl", "rust_test_suite")

rust_test_suite(
    name = "rational",
    srcs = glob([
        "rational/rational_number/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//deep_causality_algebra",
        "//deep_causality_num",
        "//deep_causality_num_rational",
    ],
)

rust_test_suite(
    name = "formalization_lean",
    srcs = glob([
        "formalization_lean/*_tests.rs",
    ]),
    tags = [
        "lean-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//deep_causality_num",
        "//deep_causality_num_rational",
    ],
)
