/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
 */

//! Phase 2 suite for [`pearson`] and [`pearson_pairwise_complete`].
//!
//! # Where the expected values come from
//!
//! Every expected `r` in this file is one of:
//!
//! * a closed form evaluated by hand, with the deviations, their sums of squares and their cross
//!   product written out in the test's comment so the arithmetic can be checked without running
//!   anything;
//! * an algebraic invariant of the coefficient — symmetry in its two arguments, invariance under a
//!   positive affine map, a sign flip under a negative one, the `[-1, 1]` bound;
//! * a property over a family generated by a linear congruential recurrence, which shares no
//!   expression with the correlation code.
//!
//! No expected value is produced by calling either function under test, and no test retypes the
//! correlation formula in an assertion. The one place a function under test appears on both sides
//! is `test_pairwise_complete_matches_pearson_over_the_filtered_pairs`, which the task requires:
//! it answers "does deletion agree with dense evaluation" and is paired, in the same test, with the
//! hand-computed value that pins both to the mathematics.
//!
//! # Readings taken where the doc comment is silent
//!
//! 1. **Fewer than two observations.** `pearson`'s doc pins the zero-variance case and nothing
//!    else. The reading asserted here is `n == 0` (nothing to correlate at all) is
//!    `EmptyInput`, and `0 < n < 2` is `InsufficientSamples` — that variant is documented as
//!    "fewer observations than the statistic's degrees of freedom require", and a correlation
//!    needs two points before "how they co-vary" means anything. It is also the split the absorbed
//!    implementation made: `mrmr_utils.rs:92` refuses `n < 2` *before* it reaches the vanishing
//!    denominator at `:101`, so the zero-variance convention applies at `n >= 2` and not below.
//!    That precedence matters, because a single observation has zero variance and would otherwise
//!    fall into the `Ok((0, n))` convention.
//! 2. **The same split after pairwise deletion.** The count that decides is the count of surviving
//!    pairs, not the length of the input slices.
//! 3. **A non-finite input.** The doc is silent, and this suite deliberately does not force a
//!    choice between refusing it and propagating it. What it does pin is that a `NaN` must not be
//!    laundered into a plausible number: either a typed `NonFiniteInput`, or an `r` that is itself
//!    `NaN`. Returning the zero-variance sentinel for a `NaN` denominator — which is what a
//!    `if !(denominator > 0)` guard would do — is the defect this rules out.
//!
//! # Corner cases
//!
//! | Row | Class | Test |
//! |---|---|---|
//! | A | Empty input | `test_empty_input_is_empty_input_error`, `test_pairwise_complete_empty_is_empty_input` |
//! | B | Single element | `test_single_observation_is_insufficient_samples`, `test_pairwise_complete_with_one_surviving_pair_is_insufficient_samples` |
//! | C | Two quantities coincide | `test_perfect_positive_correlation_is_exactly_one` (y is an exact affine image of x), `test_zero_variance_returns_ok_zero_not_an_error` (a constant column: every value tied) |
//! | D | An index expression degenerates | `test_zero_variance_returns_ok_zero_not_an_error` — the denominator `sqrt(Sxx*Syy)` is the only compound expression here and this is where it collapses to zero; `test_single_observation_is_insufficient_samples` collapses the `n - 1` degrees of freedom |
//! | E | Documented threshold, both sides | `test_zero_variance_returns_ok_zero_not_an_error` (at the threshold: variance exactly zero) and `test_variance_just_above_zero_is_not_the_zero_sentinel` (just above it: a sample that differs in one place by `2^-10`) |
//! | F | Zero | `test_uncorrelated_sample_is_exactly_zero` — an `r` of exactly zero that is *not* the zero-variance sentinel, so the sentinel is never the only place zero is pinned |
//! | G | Negative | `test_hand_computed_r_with_negative_observations`, `test_perfect_negative_correlation_is_exactly_minus_one`, `test_hand_computed_r_on_a_small_sample` (the -0.8 half) |
//! | H | Exact domain boundary | `r` has no probability argument, so "exactly 0 or 1" reads as the ends of `r`'s own range: `test_perfect_positive_correlation_is_exactly_one` and `test_perfect_negative_correlation_is_exactly_minus_one` sit on `+1` and `-1`, and `test_r_is_bounded_by_one_over_a_generated_family` shows the interior never leaves them |
//! | I | Non-finite | `test_non_finite_observation_is_not_laundered` (NaN, +inf, -inf) |
//! | J | Overflow and underflow reach | `test_extreme_magnitudes_preserve_perfect_correlation` and `test_tiny_magnitudes_preserve_perfect_correlation`, each with a scale chosen per precision so that the *sums of squares* stay in range while their *product* does not |
//! | K | f32, f64, Float106 | every test below calls a generic helper three times, with a tolerance per precision |

// The bound is `RealField`, and `Real`'s analytic surface (`abs`, `is_nan`, `is_finite`) and
// `ToPrimitive`'s `to_f64` reach these tests through its supertraits, so neither name is imported
// separately.
use deep_causality_algebra::{Real, RealField};
use deep_causality_num::lift;
use deep_causality_num::{Float106, FromPrimitive};
use deep_causality_stats::utils_tests::lift_array;
use deep_causality_stats::utils_tests::precision::{F32, F64, F106};
use deep_causality_stats::{StatsError, StatsErrorEnum, pearson, pearson_pairwise_complete};

// -------------------------------------------------------------------------------------------
// Helpers. None of these computes a correlation, or any part of one.
// -------------------------------------------------------------------------------------------

/// Unwraps an expected `Ok`, reporting the typed error rather than requiring `Debug` on `T`.
fn expect_ok<T>(result: Result<(T, usize), StatsError>, what: &str) -> (T, usize) {
    match result {
        Ok(pair) => pair,
        Err(StatsError(e)) => panic!("{what}: expected Ok, got Err({e:?})"),
    }
}

/// Asserts `|actual - expected| <= tol`, printing both through `ToPrimitive` so the message works
/// at every precision. A `NaN` actual fails, because `NaN <= tol` is false.
fn assert_close<T>(actual: T, expected: T, tol: f64, what: &str)
where
    T: RealField + FromPrimitive,
{
    let diff = (actual - expected).abs();
    assert!(
        diff <= lift::<T>(tol),
        "{what}: got {}, expected {}, tolerance {tol}",
        actual.to_f64().unwrap_or(f64::NAN),
        expected.to_f64().unwrap_or(f64::NAN)
    );
}

/// A deterministic pseudo-random family from a linear congruential recurrence.
///
/// The recurrence is integer arithmetic on `u64` with the multiplier and increment of Knuth's
/// MMIX generator. It shares no expression with the correlation code, and nothing here is
/// asserted against a value it produces — only against bounds and symmetries.
///
/// The mapping to `f64` takes 24 bits and divides by `2^23`, so every sample is an exact binary
/// fraction in `[-1, 1)` and lifts losslessly into `f32`, `f64` and `Float106` alike.
fn lcg_family(seed: u64, len: usize) -> Vec<f64> {
    let mut state = seed;
    (0..len)
        .map(|_| {
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1_442_695_040_888_963_407);
            let bits = (state >> 40) as f64; // 24 bits: 0 ..= 16_777_215
            bits / 8_388_608.0 - 1.0
        })
        .collect()
}

/// Wraps every element as `Some`, for the pairwise-complete fixtures.
fn all_present<T: Copy>(xs: &[T]) -> Vec<Option<T>> {
    xs.iter().map(|&v| Some(v)).collect()
}

/// `a * x + b`, elementwise, built in the working scalar.
fn affine<T>(xs: &[T], a: f64, b: f64) -> Vec<T>
where
    T: RealField + FromPrimitive,
{
    let a = lift::<T>(a);
    let b = lift::<T>(b);
    xs.iter().map(|&x| a * x + b).collect()
}

/// `x + x`, elementwise. Doubling is exact in binary floating point at every precision, so the
/// result is a perfect affine image of `xs` with no rounding anywhere in the construction.
fn doubled<T>(xs: &[T]) -> Vec<T>
where
    T: RealField + FromPrimitive,
{
    xs.iter().map(|&x| x + x).collect()
}

// -------------------------------------------------------------------------------------------
// Perfect correlation: the ends of the range, exactly.
// -------------------------------------------------------------------------------------------

/// x = [1, 2, 3, 4, 5], y = 2x + 3 = [5, 7, 9, 11, 13].
///
/// Closed form, by hand:
///   x̄ = 15/5 = 3      dx = [-2, -1, 0, 1, 2]     Σdx² = 4+1+0+1+4 = 10
///   ȳ = 45/5 = 9      dy = [-4, -2, 0, 2, 4]     Σdy² = 16+4+0+4+16 = 40
///   Σdxdy = 8 + 2 + 0 + 2 + 8 = 20
///   r = Σdxdy / √(Σdx²·Σdy²) = 20 / √400 = 20/20 = 1
///
/// Asserted as an exact equality, not within a tolerance. Every quantity above is a small integer,
/// exact in `f32`, `f64` and `Float106`, and √400 = 20 is exact in each; the identity `r = 1` at a
/// perfect linear relationship is the boundary of the coefficient's range, and a caller ranking
/// features by `|r|` (the use the doc comment describes) must be able to recognise it by equality.
fn check_perfect_positive<T>()
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0, 5.0]);
    let y = lift_array::<T>(&[5.0, 7.0, 9.0, 11.0, 13.0]);

    let (r, n) = expect_ok(pearson(&x, &y), "perfect positive");

    // 1.0: the closed form above.
    assert!(
        r == lift::<T>(1.0),
        "y = 2x + 3 must correlate at exactly 1, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    // 5: the number of pairs supplied.
    assert_eq!(n, 5, "the count is the number of pairs used");
}

#[test]
fn test_perfect_positive_correlation_is_exactly_one() {
    check_perfect_positive::<f32>();
    check_perfect_positive::<f64>();
    check_perfect_positive::<Float106>();
}

/// x = [1, 2, 3, 4, 5], y = -2x + 3 = [1, -1, -3, -5, -7].
///
/// Closed form, by hand:
///   x̄ = 3            dx = [-2, -1, 0, 1, 2]      Σdx² = 10
///   ȳ = -15/5 = -3   dy = [4, 2, 0, -2, -4]      Σdy² = 16+4+0+4+16 = 40
///   Σdxdy = -8 - 2 + 0 - 2 - 8 = -20
///   r = -20 / √400 = -1
fn check_perfect_negative<T>()
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0, 5.0]);
    let y = lift_array::<T>(&[1.0, -1.0, -3.0, -5.0, -7.0]);

    let (r, n) = expect_ok(pearson(&x, &y), "perfect negative");

    // -1.0: the closed form above.
    assert!(
        r == lift::<T>(-1.0),
        "y = -2x + 3 must correlate at exactly -1, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    // 5: the number of pairs supplied.
    assert_eq!(n, 5, "the count is the number of pairs used");
}

#[test]
fn test_perfect_negative_correlation_is_exactly_minus_one() {
    check_perfect_negative::<f32>();
    check_perfect_negative::<f64>();
    check_perfect_negative::<Float106>();
}

// -------------------------------------------------------------------------------------------
// Hand-computed values on samples small enough to check by eye.
// -------------------------------------------------------------------------------------------

/// x = [1, 2, 3, 4], y = [1, 3, 2, 4] and its reflection y' = 5 - y = [4, 2, 3, 1].
///
/// Closed form, by hand:
///   x̄ = 10/4 = 2.5   dx  = [-1.5, -0.5,  0.5, 1.5]   Σdx²  = 2.25+0.25+0.25+2.25 = 5
///   ȳ = 10/4 = 2.5   dy  = [-1.5,  0.5, -0.5, 1.5]   Σdy²  = 2.25+0.25+0.25+2.25 = 5
///   Σdxdy = 2.25 - 0.25 - 0.25 + 2.25 = 4
///   r = 4 / √(5·5) = 4/5 = 0.8
///
/// Reflecting y about its mean negates every dy and therefore negates Σdxdy while leaving Σdy²
/// alone, so r' = -4/5 = -0.8.
fn check_hand_computed_small_sample<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let y = lift_array::<T>(&[1.0, 3.0, 2.0, 4.0]);
    let y_reflected = lift_array::<T>(&[4.0, 2.0, 3.0, 1.0]);

    let (r, n) = expect_ok(pearson(&x, &y), "hand-computed 0.8");
    // 0.8: 4/5 from the working above.
    assert_close(r, lift::<T>(0.8), tol, "r for x=[1,2,3,4], y=[1,3,2,4]");
    // 4: the number of pairs supplied.
    assert_eq!(n, 4, "the count is the number of pairs used");

    let (r_reflected, n_reflected) = expect_ok(pearson(&x, &y_reflected), "hand-computed -0.8");
    // -0.8: -4/5, the reflection argument above.
    assert_close(
        r_reflected,
        lift::<T>(-0.8),
        tol,
        "r for x=[1,2,3,4], y=[4,2,3,1]",
    );
    assert_eq!(n_reflected, 4, "the count is the number of pairs used");
}

#[test]
fn test_hand_computed_r_on_a_small_sample() {
    check_hand_computed_small_sample::<f32>(F32.literal);
    check_hand_computed_small_sample::<f64>(F64.literal);
    check_hand_computed_small_sample::<Float106>(F106.literal);
}

/// Row G: observations on both sides of zero, with both means exactly zero.
///
/// x = [-2, -1, 1, 2], y = [-1, -2, 1, 2].
///
/// Closed form, by hand:
///   x̄ = 0   dx = x   Σdx² = 4+1+1+4 = 10
///   ȳ = 0   dy = y   Σdy² = 1+4+1+4 = 10
///   Σdxdy = (-2)(-1) + (-1)(-2) + (1)(1) + (2)(2) = 2 + 2 + 1 + 4 = 9
///   r = 9 / √(10·10) = 9/10 = 0.9
fn check_hand_computed_negative_observations<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[-2.0, -1.0, 1.0, 2.0]);
    let y = lift_array::<T>(&[-1.0, -2.0, 1.0, 2.0]);

    let (r, n) = expect_ok(pearson(&x, &y), "hand-computed 0.9 with negatives");

    // 0.9: 9/10 from the working above.
    assert_close(r, lift::<T>(0.9), tol, "r over observations spanning zero");
    // 4: the number of pairs supplied.
    assert_eq!(n, 4, "the count is the number of pairs used");
}

#[test]
fn test_hand_computed_r_with_negative_observations() {
    check_hand_computed_negative_observations::<f32>(F32.literal);
    check_hand_computed_negative_observations::<f64>(F64.literal);
    check_hand_computed_negative_observations::<Float106>(F106.literal);
}

/// Row F: an `r` of exactly zero that is *not* the zero-variance sentinel.
///
/// x = [1, 2, 3, 4], y = [1, 2, 2, 1].
///
/// Closed form, by hand:
///   x̄ = 2.5   dx = [-1.5, -0.5, 0.5, 1.5]      Σdx² = 5
///   ȳ = 1.5   dy = [-0.5,  0.5, 0.5, -0.5]     Σdy² = 4·0.25 = 1   (non-zero: y is not constant)
///   Σdxdy = 0.75 - 0.25 + 0.25 - 0.75 = 0
///   r = 0 / √(5·1) = 0
///
/// Both variances are strictly positive here, so the zero comes from the numerator. That keeps
/// the suite from pinning "zero" only where the denominator vanishes.
fn check_uncorrelated_is_exactly_zero<T>()
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let y = lift_array::<T>(&[1.0, 2.0, 2.0, 1.0]);

    let (r, n) = expect_ok(pearson(&x, &y), "uncorrelated sample");

    // 0.0: the closed form above. Every term of Σdxdy is an exact binary fraction and they cancel
    // in pairs, so the sum is exactly zero at every precision — no tolerance needed.
    assert!(
        r == lift::<T>(0.0),
        "a vanishing cross product must give exactly 0, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    // 4: the number of pairs supplied.
    assert_eq!(n, 4, "the count is the number of pairs used");
}

#[test]
fn test_uncorrelated_sample_is_exactly_zero() {
    check_uncorrelated_is_exactly_zero::<f32>();
    check_uncorrelated_is_exactly_zero::<f64>();
    check_uncorrelated_is_exactly_zero::<Float106>();
}

// -------------------------------------------------------------------------------------------
// The zero-variance convention, and the threshold either side of it.
// -------------------------------------------------------------------------------------------

/// The documented convention, quoted from `pearson`'s doc comment:
///
/// > When either sample has zero variance the correlation is undefined — the denominator vanishes
/// > — and this returns `Ok((0, n))` rather than an error. That is the absorbed implementation's
/// > convention, preserved deliberately: its caller ranks features by `|r|` and a zero rank means
/// > "carries no information", which is the right answer for a constant column.
///
/// So: not an error, not `NaN`, and the count is still the number of pairs seen. Asserted for a
/// constant x against a varying y, a varying x against a constant y, and both constant — because
/// an implementation that guards only one of the two denominators passes the first and fails the
/// second.
fn check_zero_variance_is_ok_zero<T>()
where
    T: RealField + FromPrimitive,
{
    let constant = lift_array::<T>(&[2.0, 2.0, 2.0, 2.0]);
    let varying = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let other_constant = lift_array::<T>(&[-7.5, -7.5, -7.5, -7.5]);

    let zero = lift::<T>(0.0);

    // Constant first argument.
    let (r, n) = expect_ok(pearson(&constant, &varying), "constant x");
    // 0.0: the convention quoted above, not a computed quantity.
    assert!(
        r == zero,
        "a constant x must give exactly 0, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    // 4: the pairs are still counted, even though r carries no information.
    assert_eq!(n, 4, "the count reports the pairs seen, not the pairs used");

    // Constant second argument.
    let (r, n) = expect_ok(pearson(&varying, &constant), "constant y");
    assert!(
        r == zero,
        "a constant y must give exactly 0, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    assert_eq!(n, 4, "the count reports the pairs seen");

    // Both constant, and at different constants, so no accidental agreement of the two columns
    // can stand in for the guard.
    let (r, n) = expect_ok(pearson(&constant, &other_constant), "both constant");
    assert!(
        r == zero,
        "two constant columns must give exactly 0, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    assert_eq!(n, 4, "the count reports the pairs seen");
}

#[test]
fn test_zero_variance_returns_ok_zero_not_an_error() {
    check_zero_variance_is_ok_zero::<f32>();
    check_zero_variance_is_ok_zero::<f64>();
    check_zero_variance_is_ok_zero::<Float106>();
}

/// Row E, the other side of the same threshold: the smallest departure from a constant column
/// that all three precisions represent exactly.
///
/// x = [1, 1, 1, 1 + 2^-10] = [1, 1, 1, 1.0009765625], and y = x.
///
/// Closed form, by hand:
///   x̄ = 1 + 2^-12                       (the four values sum to 4 + 2^-10)
///   dx = [-2^-12, -2^-12, -2^-12, 3·2^-12]
///   Σdx² = 3·2^-24 + 9·2^-24 = 12·2^-24 = 3·2^-22, exact in an f32 significand
///   y = x, so Σdy² = Σdxdy = Σdx² = S > 0
///   r = S / √(S·S) = S/S = 1
///
/// The variance is 7.15…e-7 rather than zero, so the `Ok((0, n))` convention must *not* fire: the
/// documented trigger is a vanishing denominator, not a small one.
fn check_variance_just_above_zero<T>()
where
    T: RealField + FromPrimitive,
{
    // 2^-10 = 0.0009765625, exact in every binary format with 10 or more significand bits.
    let x = lift_array::<T>(&[1.0, 1.0, 1.0, 1.0009765625]);
    let y = x.clone();

    let (r, n) = expect_ok(pearson(&x, &y), "variance just above zero");

    // 1.0: the closed form above. A sample correlated with itself is perfectly correlated however
    // small its spread, so this is the boundary value +1 and not the zero sentinel.
    assert!(
        r == lift::<T>(1.0),
        "a non-constant column must correlate with itself at exactly 1, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    // 4: the number of pairs supplied.
    assert_eq!(n, 4, "the count is the number of pairs used");
}

#[test]
fn test_variance_just_above_zero_is_not_the_zero_sentinel() {
    check_variance_just_above_zero::<f32>();
    check_variance_just_above_zero::<f64>();
    check_variance_just_above_zero::<Float106>();
}

// -------------------------------------------------------------------------------------------
// Invariants over a generated family.
// -------------------------------------------------------------------------------------------

/// The bound `-1 <= r <= 1` — the Cauchy–Schwarz inequality applied to the centred samples, which
/// is what the coefficient is a normalisation by. Asserted over eight independent samples from
/// the LCG family, none of which is constant, so none is the zero-variance case.
///
/// The tolerance appears on the bound because a correctly computed `r` may land one unit in the
/// last place outside it; a value that leaves the range by more than that is a defect.
fn check_r_is_bounded<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let one = lift::<T>(1.0);
    let slack = lift::<T>(tol);

    for seed in 0..8u64 {
        let x = lift_array::<T>(&lcg_family(seed * 2 + 1, 16));
        let y = lift_array::<T>(&lcg_family(seed * 2 + 2, 16));

        let (r, n) = expect_ok(pearson(&x, &y), "generated family");

        assert!(r.is_finite(), "r must be finite for a finite sample");
        // 1.0 here is the range endpoint, not a computed expectation: |r| <= 1 for every sample.
        assert!(
            r.abs() <= one + slack,
            "seed {seed}: |r| left [-1, 1]: {}",
            r.to_f64().unwrap_or(f64::NAN)
        );
        // 16: the generated length.
        assert_eq!(n, 16, "the count is the generated sample length");
    }
}

#[test]
fn test_r_is_bounded_by_one_over_a_generated_family() {
    check_r_is_bounded::<f32>(F32.native);
    check_r_is_bounded::<f64>(F64.native);
    check_r_is_bounded::<Float106>(F106.native);
}

/// Symmetry: `r(x, y) = r(y, x)`. The coefficient is a normalised inner product of the two centred
/// samples, and an inner product is symmetric, so exchanging the arguments cannot move it.
fn check_r_is_symmetric<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    // A hand-written pair and two generated ones, so the property is not tested at one shape only.
    let cases: [(Vec<T>, Vec<T>); 3] = [
        (
            lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]),
            lift_array::<T>(&[1.0, 3.0, 2.0, 4.0]),
        ),
        (
            lift_array::<T>(&lcg_family(11, 12)),
            lift_array::<T>(&lcg_family(12, 12)),
        ),
        (
            lift_array::<T>(&lcg_family(13, 9)),
            lift_array::<T>(&lcg_family(14, 9)),
        ),
    ];

    for (i, (x, y)) in cases.iter().enumerate() {
        let (forward, n_forward) = expect_ok(pearson(x, y), "symmetry, forward");
        let (backward, n_backward) = expect_ok(pearson(y, x), "symmetry, backward");

        assert_close(forward, backward, tol, "r(x, y) against r(y, x)");
        assert_eq!(
            n_forward, n_backward,
            "case {i}: the count cannot depend on argument order"
        );
    }
}

#[test]
fn test_r_is_symmetric_in_its_arguments() {
    check_r_is_symmetric::<f32>(F32.native);
    check_r_is_symmetric::<f64>(F64.native);
    check_r_is_symmetric::<Float106>(F106.native);
}

/// Invariance under a positive affine map of either argument.
///
/// Replacing y by `a·y + b` with `a > 0` multiplies every dy by `a` and leaves the centring alone,
/// so Σdxdy scales by `a` and √Σdy² scales by `a`; the two cancel. The same holds for x. The
/// constants used are exact binary fractions (2.5, -7.5, 0.25, 100.0) so the transform introduces
/// no rounding of its own.
fn check_positive_affine_invariance<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let y = lift_array::<T>(&[1.0, 3.0, 2.0, 4.0]);

    let (base, n_base) = expect_ok(pearson(&x, &y), "affine base");

    let y_scaled = affine(&y, 2.5, -7.5);
    let (r_y, n_y) = expect_ok(pearson(&x, &y_scaled), "affine on y");
    assert_close(r_y, base, tol, "r is invariant under 2.5·y - 7.5");
    assert_eq!(n_y, n_base, "an affine map cannot change the count");

    let x_scaled = affine(&x, 0.25, 100.0);
    let (r_x, n_x) = expect_ok(pearson(&x_scaled, &y), "affine on x");
    assert_close(r_x, base, tol, "r is invariant under 0.25·x + 100");
    assert_eq!(n_x, n_base, "an affine map cannot change the count");
}

#[test]
fn test_r_is_invariant_under_a_positive_affine_map() {
    check_positive_affine_invariance::<f32>(F32.native);
    check_positive_affine_invariance::<f64>(F64.native);
    check_positive_affine_invariance::<Float106>(F106.native);
}

/// A negative affine map flips the sign.
///
/// With `a < 0` every dy is negated and scaled by `|a|`: Σdxdy picks up the sign, √Σdy² does not,
/// so `r` is negated exactly. Checked on each argument in turn.
fn check_negative_affine_flips_sign<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let y = lift_array::<T>(&[1.0, 3.0, 2.0, 4.0]);

    let (base, _) = expect_ok(pearson(&x, &y), "sign-flip base");
    let negated = -base;

    let y_flipped = affine(&y, -2.0, 6.0);
    let (r_y, n_y) = expect_ok(pearson(&x, &y_flipped), "sign flip on y");
    assert_close(r_y, negated, tol, "r flips sign under -2·y + 6");
    // 4: the number of pairs supplied.
    assert_eq!(n_y, 4, "a sign flip cannot change the count");

    let x_flipped = affine(&x, -0.5, -3.0);
    let (r_x, n_x) = expect_ok(pearson(&x_flipped, &y), "sign flip on x");
    assert_close(r_x, negated, tol, "r flips sign under -0.5·x - 3");
    assert_eq!(n_x, 4, "a sign flip cannot change the count");
}

#[test]
fn test_r_flips_sign_under_a_negative_affine_map() {
    check_negative_affine_flips_sign::<f32>(F32.native);
    check_negative_affine_flips_sign::<f64>(F64.native);
    check_negative_affine_flips_sign::<Float106>(F106.native);
}

// -------------------------------------------------------------------------------------------
// Refused inputs.
// -------------------------------------------------------------------------------------------

/// Row A: no observations at all.
fn check_empty_is_empty_input<T>()
where
    T: RealField + FromPrimitive,
{
    let empty: [T; 0] = [];

    match pearson(&empty, &empty) {
        Err(StatsError(StatsErrorEnum::EmptyInput(_))) => {}
        Err(StatsError(other)) => panic!("expected EmptyInput, got {other:?}"),
        Ok((_, n)) => panic!("expected EmptyInput, got Ok with count {n}"),
    }
}

#[test]
fn test_empty_input_is_empty_input_error() {
    check_empty_is_empty_input::<f32>();
    check_empty_is_empty_input::<f64>();
    check_empty_is_empty_input::<Float106>();
}

/// Two samples that do not pair up. Checked in both directions, because a length check written
/// against one argument's length only is a real defect that a single direction misses.
///
/// The case where one slice is empty *and* the lengths differ is deliberately not asserted: the
/// doc comment fixes no precedence between `EmptyInput` and `DimensionMismatch`, and pinning one
/// would invent a contract rather than test it.
fn check_length_mismatch<T>()
where
    T: RealField + FromPrimitive,
{
    let short = lift_array::<T>(&[1.0, 2.0, 3.0]);
    let long = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);

    match pearson(&short, &long) {
        Err(StatsError(StatsErrorEnum::DimensionMismatch(_))) => {}
        Err(StatsError(other)) => panic!("expected DimensionMismatch for 3 vs 4, got {other:?}"),
        Ok((_, n)) => panic!("expected DimensionMismatch for 3 vs 4, got Ok with count {n}"),
    }

    match pearson(&long, &short) {
        Err(StatsError(StatsErrorEnum::DimensionMismatch(_))) => {}
        Err(StatsError(other)) => panic!("expected DimensionMismatch for 4 vs 3, got {other:?}"),
        Ok((_, n)) => panic!("expected DimensionMismatch for 4 vs 3, got Ok with count {n}"),
    }
}

#[test]
fn test_length_mismatch_is_dimension_mismatch() {
    check_length_mismatch::<f32>();
    check_length_mismatch::<f64>();
    check_length_mismatch::<Float106>();
}

/// Row B: one observation.
///
/// The reading asserted here is stated in the module comment: a single pair is `InsufficientSamples`,
/// and the zero-variance convention applies only from two observations upward. A single pair has
/// zero spread in both columns, so this is exactly where the two readings differ, and the absorbed
/// implementation resolved it by refusing `n < 2` before it looked at the denominator.
fn check_single_observation<T>()
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[3.5]);
    let y = lift_array::<T>(&[-1.25]);

    match pearson(&x, &y) {
        Err(StatsError(StatsErrorEnum::InsufficientSamples(_))) => {}
        Err(StatsError(other)) => panic!("expected InsufficientSamples for n = 1, got {other:?}"),
        Ok((_, n)) => panic!("expected InsufficientSamples for n = 1, got Ok with count {n}"),
    }
}

#[test]
fn test_single_observation_is_insufficient_samples() {
    check_single_observation::<f32>();
    check_single_observation::<f64>();
    check_single_observation::<Float106>();
}

/// Row I: a non-finite observation.
///
/// The doc comment does not say whether such an input is refused or propagated, so this pins the
/// disjunction rather than inventing a choice: either a typed `NonFiniteInput`, or an `r` that is
/// itself `NaN`. What it rules out is the laundering case — a `NaN` denominator failing a
/// `> 0` test and falling into the `Ok((0, n))` zero-variance convention, which would report
/// "carries no information" for data that is in fact corrupt.
fn check_non_finite_is_not_laundered<T>()
where
    T: RealField + FromPrimitive,
{
    let y = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);

    for (label, contaminated) in [
        ("NaN", lift_array::<T>(&[1.0, 2.0, f64::NAN, 4.0])),
        ("+inf", lift_array::<T>(&[1.0, 2.0, f64::INFINITY, 4.0])),
        ("-inf", lift_array::<T>(&[1.0, 2.0, f64::NEG_INFINITY, 4.0])),
    ] {
        match pearson(&contaminated, &y) {
            Err(StatsError(StatsErrorEnum::NonFiniteInput(_))) => {}
            Err(StatsError(other)) => {
                panic!("{label}: an error here must be NonFiniteInput, got {other:?}")
            }
            Ok((r, _)) => assert!(
                r.is_nan(),
                "{label}: a non-finite observation must not yield the finite value {}",
                r.to_f64().unwrap_or(f64::NAN)
            ),
        }
    }
}

#[test]
fn test_non_finite_observation_is_not_laundered() {
    check_non_finite_is_not_laundered::<f32>();
    check_non_finite_is_not_laundered::<f64>();
    check_non_finite_is_not_laundered::<Float106>();
}

// -------------------------------------------------------------------------------------------
// Row J: reach at the type's own extremes.
//
// Both tests use x = [1, 2, 3, 4]·s and y = x + x, so the answer is the invariant r = 1 for every
// scale: `r` is invariant under a positive scaling of either argument, and doubling is exact in
// binary floating point, so no rounding enters the construction.
//
// The scales are chosen per precision from the type's own exponent range, so that the sums of
// squares stay representable while their *product* does not:
//
//   Σdx² = 5s²   and   Σdy² = 20s²   (dx = [-1.5, -0.5, 0.5, 1.5]·s), so their product is 100s⁴.
//
//   f32   (max 3.4e38, min normal 1.2e-38): s = 1e15  → 5s² = 5e30,   100s⁴ = 1e62  → +inf
//                                            s = 1e-15 → 5s² = 5e-30,  100s⁴ = 1e-58 → 0
//   f64   (max 1.8e308, min normal 2.2e-308): s = 1e100  → 5s² = 5e200,  100s⁴ = 1e402  → +inf
//                                              s = 1e-120 → 5s² = 5e-240, 100s⁴ = 1e-478 → 0
//   Float106 carries an f64 exponent, so it takes the f64 scales.
//
// An implementation that forms `Σdx²·Σdy²` before taking the root therefore divides by inf or by
// zero and cannot return 1; one that scales the deviations, or takes the two roots separately,
// stays in range. That is the vector_norm_l2 failure mode the corner-case table's row J names.
// -------------------------------------------------------------------------------------------

fn check_extreme_magnitudes<T>(scale: f64, tol: f64)
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[scale, 2.0 * scale, 3.0 * scale, 4.0 * scale]);
    let y = doubled(&x);

    let (r, n) = expect_ok(pearson(&x, &y), "extreme magnitudes");

    // 1.0: y = 2x is a positive scaling of x, and r is invariant under one, so the perfect
    // correlation of the unscaled sample is preserved.
    assert_close(r, lift::<T>(1.0), tol, "r at an extreme scale");
    // 4: the number of pairs supplied.
    assert_eq!(n, 4, "the count is the number of pairs used");
}

#[test]
fn test_extreme_magnitudes_preserve_perfect_correlation() {
    check_extreme_magnitudes::<f32>(1e15, F32.native);
    check_extreme_magnitudes::<f64>(1e100, F64.native);
    check_extreme_magnitudes::<Float106>(1e100, F106.native);
}

#[test]
fn test_tiny_magnitudes_preserve_perfect_correlation() {
    check_extreme_magnitudes::<f32>(1e-15, F32.native);
    check_extreme_magnitudes::<f64>(1e-120, F64.native);
    check_extreme_magnitudes::<Float106>(1e-120, F106.native);
}

// -------------------------------------------------------------------------------------------
// Row J, one step further out: the centred sums themselves leave the type.
//
// The two tests above are scaled so that `Σdx²` and `Σdy²` stay representable and only their
// *product* does not. Past that there is a second band, where the sums of squares are the things
// that go: with dx = [-1.5, -0.5, 0.5, 1.5]·s,
//
//   f32   (max 3.4e38, min normal 1.2e-38): s = 1e30   → 2.25s²  = 2.3e60  → +inf
//                                            s = 1e-30  → 2.25s²  = 2.3e-60 → 0
//   f64   (max 1.8e308, min normal 2.2e-308): s = 1e200  → 2.25s² = 2.3e400 → +inf
//                                              s = 1e-200 → 2.25s² = 2.3e-400 → 0
//   Float106 carries an f64 exponent, so it takes the f64 scales.
//
// The answer is the same invariant `r = 1`: `r` is unchanged by a positive scaling of either
// sample, and the scale is the only thing that differs from the fixture used above. Two distinct
// wrong answers are on offer here and both are worse than an error: `Σdx² = +∞` divides `∞` by
// `∞` and returns `NaN`, and `Σdx² = 0` reaches the zero-variance exit and returns `Ok(0)` — the
// documented answer for a *constant* column — for a sample that is perfectly correlated.
// -------------------------------------------------------------------------------------------

#[test]
fn test_overflowing_centred_sums_preserve_perfect_correlation() {
    check_extreme_magnitudes::<f32>(1e30, F32.native);
    check_extreme_magnitudes::<f64>(1e200, F64.native);
    check_extreme_magnitudes::<Float106>(1e200, F106.native);
}

#[test]
fn test_underflowing_centred_sums_preserve_perfect_correlation() {
    check_extreme_magnitudes::<f32>(1e-30, F32.native);
    check_extreme_magnitudes::<f64>(1e-200, F64.native);
    check_extreme_magnitudes::<Float106>(1e-200, F106.native);
}

/// The zero-variance convention, at a constant column the *sum* of which is not representable.
///
/// Provenance: this function's documented answer for a constant column, quoted in `pearson`'s doc:
///
/// > When either sample has zero variance the correlation is undefined ... and this returns
/// > `Ok((0, n))` rather than an error.
///
/// A column of three copies of the type's maximum is constant, so that is the answer. It is also a
/// column whose left-to-right sum is `+∞`, and a mean taken from that sum centres the column on
/// nothing: every deviation is then `MAX − ∞ = −∞`, `Σdx²` is `+∞`, and `r` comes back as `NaN`
/// from a column that carries no information at all.
fn check_constant_column_at_the_type_maximum<T>(max: f64)
where
    T: RealField + FromPrimitive,
{
    let constant = lift_array::<T>(&[max, max, max]);
    let varying = lift_array::<T>(&[1.0, 2.0, 3.0]);

    let (r, n) = expect_ok(pearson(&constant, &varying), "a constant column at MAX");
    assert!(
        r == lift::<T>(0.0),
        "a constant column returned {:?}, not the documented zero",
        r.to_f64().unwrap_or(f64::NAN)
    );
    assert_eq!(n, 3, "the count is the number of pairs used");

    // The same both ways round: the convention is about either sample, not about the first.
    let (r, _) = expect_ok(
        pearson(&varying, &constant),
        "a constant second column at MAX",
    );
    assert!(
        r == lift::<T>(0.0),
        "a constant second column returned {:?}, not the documented zero",
        r.to_f64().unwrap_or(f64::NAN)
    );
}

#[test]
fn test_constant_column_at_the_type_maximum_is_ok_zero() {
    check_constant_column_at_the_type_maximum::<f32>(F32.max_finite);
    check_constant_column_at_the_type_maximum::<f64>(F64.max_finite);
    check_constant_column_at_the_type_maximum::<Float106>(F106.max_finite);
}

// -------------------------------------------------------------------------------------------
// pearson_pairwise_complete
// -------------------------------------------------------------------------------------------

/// The missing-data policy, quoted from the doc comment:
///
/// > a pair contributes only when both entries are `Some`, and the returned count says how many
/// > did.
///
/// The fixture has six rows and four surviving pairs:
///
///   index | x        | y        | survives
///   ------|----------|----------|---------
///     0   | Some(1)  | Some(1)  | yes
///     1   | None     | Some(7)  | no  — x missing, so y's 7 is discarded with it
///     2   | Some(2)  | Some(3)  | yes
///     3   | Some(3)  | Some(2)  | yes
///     4   | Some(4)  | Some(4)  | yes
///     5   | Some(9)  | None     | no  — y missing, so x's 9 is discarded with it
///
/// The survivors are x = [1, 2, 3, 4] against y = [1, 3, 2, 4], the sample computed by hand in
/// `check_hand_computed_small_sample`: r = 4/5 = 0.8, over 4 pairs and not 6.
///
/// The two discarded partners (7 and 9) are far outside the surviving range on purpose. An
/// implementation that keeps a half-present row — by substituting zero, or by dropping only the
/// missing entry and letting the columns slip out of alignment — moves `r` by far more than the
/// tolerance, so the assertion detects it rather than merely tolerating it.
fn check_pairwise_drops_half_present_rows<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    // Spelled out row by row, in the order of the table above.
    let col_x = lift_array::<T>(&[1.0, 0.0, 2.0, 3.0, 4.0, 9.0]);
    let col_y = lift_array::<T>(&[1.0, 7.0, 3.0, 2.0, 4.0, 0.0]);
    let x = [
        Some(col_x[0]),
        None,
        Some(col_x[2]),
        Some(col_x[3]),
        Some(col_x[4]),
        Some(col_x[5]),
    ];
    let y = [
        Some(col_y[0]),
        Some(col_y[1]),
        Some(col_y[2]),
        Some(col_y[3]),
        Some(col_y[4]),
        None,
    ];

    let (r, n) = expect_ok(pearson_pairwise_complete(&x, &y), "pairwise deletion");

    // 0.8: 4/5, the hand computation quoted above.
    assert_close(r, lift::<T>(0.8), tol, "r over the surviving pairs");
    // 4: the four rows where both columns are Some, out of six rows supplied.
    assert_eq!(
        n, 4,
        "the count is the number of surviving pairs, not the number of rows"
    );
}

#[test]
fn test_pairwise_complete_drops_pairs_with_a_missing_partner() {
    check_pairwise_drops_half_present_rows::<f32>(F32.literal);
    check_pairwise_drops_half_present_rows::<f64>(F64.literal);
    check_pairwise_drops_half_present_rows::<Float106>(F106.literal);
}

/// Agreement with dense evaluation: deletion followed by correlation equals correlation of the
/// pairs that survive deletion, filtered here by hand rather than by the function.
///
/// This is the one test that puts a function under test on both sides, and it is required by the
/// task. It answers a different question from the test above — "does deletion change the answer"
/// rather than "is the answer right" — so the hand-computed 0.8 is asserted here as well, and it
/// is what pins the pair to the mathematics if both functions were wrong together.
fn check_pairwise_matches_dense<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let sparse_x: Vec<Option<T>> = vec![
        Some(lift::<T>(1.0)),
        None,
        Some(lift::<T>(2.0)),
        Some(lift::<T>(3.0)),
        Some(lift::<T>(4.0)),
        Some(lift::<T>(9.0)),
    ];
    let sparse_y: Vec<Option<T>> = vec![
        Some(lift::<T>(1.0)),
        Some(lift::<T>(7.0)),
        Some(lift::<T>(3.0)),
        Some(lift::<T>(2.0)),
        Some(lift::<T>(4.0)),
        None,
    ];

    // Filtered by hand, by reading the table above: rows 0, 2, 3 and 4.
    let dense_x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let dense_y = lift_array::<T>(&[1.0, 3.0, 2.0, 4.0]);

    let (sparse_r, sparse_n) = expect_ok(pearson_pairwise_complete(&sparse_x, &sparse_y), "sparse");
    let (dense_r, dense_n) = expect_ok(pearson(&dense_x, &dense_y), "dense");

    assert_close(
        sparse_r,
        dense_r,
        tol,
        "pairwise-complete against dense pearson",
    );
    assert_eq!(
        sparse_n, dense_n,
        "the surviving-pair count must equal the dense sample length"
    );
    // 0.8: 4/5, from the working in check_hand_computed_small_sample.
    assert_close(
        sparse_r,
        lift::<T>(0.8),
        tol,
        "the agreed value is the hand-computed one",
    );
}

#[test]
fn test_pairwise_complete_matches_pearson_over_the_filtered_pairs() {
    check_pairwise_matches_dense::<f32>(F32.literal);
    check_pairwise_matches_dense::<f64>(F64.literal);
    check_pairwise_matches_dense::<Float106>(F106.literal);
}

/// With nothing missing, pairwise-complete deletion deletes nothing: the count is the input length
/// and the value is the hand-computed one.
fn check_pairwise_with_nothing_missing<T>(tol: f64)
where
    T: RealField + FromPrimitive,
{
    let x = lift_array::<T>(&[1.0, 2.0, 3.0, 4.0]);
    let y = lift_array::<T>(&[1.0, 3.0, 2.0, 4.0]);

    let (r, n) = expect_ok(
        pearson_pairwise_complete(&all_present(&x), &all_present(&y)),
        "fully present",
    );

    // 0.8: 4/5, from the working in check_hand_computed_small_sample.
    assert_close(r, lift::<T>(0.8), tol, "r with nothing deleted");
    // 4: every row survives.
    assert_eq!(n, 4, "with nothing missing the count is the input length");
}

#[test]
fn test_pairwise_complete_with_nothing_missing_matches_the_hand_computed_value() {
    check_pairwise_with_nothing_missing::<f32>(F32.literal);
    check_pairwise_with_nothing_missing::<f64>(F64.literal);
    check_pairwise_with_nothing_missing::<Float106>(F106.literal);
}

/// The zero-variance convention applies to the survivors, and the count is theirs.
///
/// x = [Some(5), None, Some(5), Some(5)] against y = [Some(1), Some(9), Some(2), Some(3)]:
/// three rows survive, and in them x is constant. Per `pearson`'s documented convention that is
/// `Ok((0, n))` — with n = 3, the surviving count, not 4.
fn check_pairwise_zero_variance_among_survivors<T>()
where
    T: RealField + FromPrimitive,
{
    let five = lift::<T>(5.0);
    let x = [Some(five), None, Some(five), Some(five)];
    let y = [
        Some(lift::<T>(1.0)),
        Some(lift::<T>(9.0)),
        Some(lift::<T>(2.0)),
        Some(lift::<T>(3.0)),
    ];

    let (r, n) = expect_ok(pearson_pairwise_complete(&x, &y), "constant survivors");

    // 0.0: the zero-variance convention quoted in check_zero_variance_is_ok_zero.
    assert!(
        r == lift::<T>(0.0),
        "constant survivors must give exactly 0, got {}",
        r.to_f64().unwrap_or(f64::NAN)
    );
    // 3: rows 0, 2 and 3 survive; row 1 is deleted.
    assert_eq!(n, 3, "the count is the surviving pairs");
}

#[test]
fn test_pairwise_complete_zero_variance_among_survivors_returns_zero() {
    check_pairwise_zero_variance_among_survivors::<f32>();
    check_pairwise_zero_variance_among_survivors::<f64>();
    check_pairwise_zero_variance_among_survivors::<Float106>();
}

/// Row B after deletion: one surviving pair.
///
/// x = [Some(1), None, Some(2)] against y = [Some(1), Some(2), None] leaves row 0 alone. Per the
/// reading stated in the module comment, `0 < n < 2` is `InsufficientSamples` — and the count that
/// decides is the surviving count, even though three rows were supplied.
fn check_pairwise_one_surviving_pair<T>()
where
    T: RealField + FromPrimitive,
{
    let x = [Some(lift::<T>(1.0)), None, Some(lift::<T>(2.0))];
    let y = [Some(lift::<T>(1.0)), Some(lift::<T>(2.0)), None];

    match pearson_pairwise_complete(&x, &y) {
        Err(StatsError(StatsErrorEnum::InsufficientSamples(_))) => {}
        Err(StatsError(other)) => {
            panic!("expected InsufficientSamples for one surviving pair, got {other:?}")
        }
        Ok((_, n)) => panic!("expected InsufficientSamples for one surviving pair, got Ok({n})"),
    }
}

#[test]
fn test_pairwise_complete_with_one_surviving_pair_is_insufficient_samples() {
    check_pairwise_one_surviving_pair::<f32>();
    check_pairwise_one_surviving_pair::<f64>();
    check_pairwise_one_surviving_pair::<Float106>();
}

/// Row A after deletion: no surviving pair, from two non-empty inputs whose present entries never
/// line up, and from two entirely absent ones.
///
/// Per the reading stated in the module comment, a surviving count of zero is `EmptyInput`: the
/// statistic was asked for over no observations, which is that variant's documented meaning.
fn check_pairwise_no_surviving_pair<T>()
where
    T: RealField + FromPrimitive,
{
    // Present entries that never coincide: row 0 has no y, row 1 has no x.
    let x = [None, Some(lift::<T>(1.0))];
    let y = [Some(lift::<T>(2.0)), None];

    match pearson_pairwise_complete(&x, &y) {
        Err(StatsError(StatsErrorEnum::EmptyInput(_))) => {}
        Err(StatsError(other)) => {
            panic!("expected EmptyInput for no surviving pair, got {other:?}")
        }
        Ok((_, n)) => panic!("expected EmptyInput for no surviving pair, got Ok({n})"),
    }

    // Nothing present at all.
    let absent_x: [Option<T>; 3] = [None, None, None];
    let absent_y: [Option<T>; 3] = [None, None, None];

    match pearson_pairwise_complete(&absent_x, &absent_y) {
        Err(StatsError(StatsErrorEnum::EmptyInput(_))) => {}
        Err(StatsError(other)) => panic!("expected EmptyInput for an absent column, got {other:?}"),
        Ok((_, n)) => panic!("expected EmptyInput for an absent column, got Ok({n})"),
    }
}

#[test]
fn test_pairwise_complete_with_no_surviving_pairs_is_empty_input() {
    check_pairwise_no_surviving_pair::<f32>();
    check_pairwise_no_surviving_pair::<f64>();
    check_pairwise_no_surviving_pair::<Float106>();
}

/// Row A: empty slices.
fn check_pairwise_empty<T>()
where
    T: RealField + FromPrimitive,
{
    let empty: [Option<T>; 0] = [];

    match pearson_pairwise_complete(&empty, &empty) {
        Err(StatsError(StatsErrorEnum::EmptyInput(_))) => {}
        Err(StatsError(other)) => panic!("expected EmptyInput, got {other:?}"),
        Ok((_, n)) => panic!("expected EmptyInput, got Ok with count {n}"),
    }
}

#[test]
fn test_pairwise_complete_empty_is_empty_input() {
    check_pairwise_empty::<f32>();
    check_pairwise_empty::<f64>();
    check_pairwise_empty::<Float106>();
}

/// Slices that cannot be paired at all. Checked in both directions, as for `pearson`.
///
/// The lengths are compared before deletion: two columns of different length are not a sample with
/// missing entries, they are a caller error, and the shape variant is what says so.
fn check_pairwise_length_mismatch<T>()
where
    T: RealField + FromPrimitive,
{
    let short = [Some(lift::<T>(1.0)), Some(lift::<T>(2.0))];
    let long = [
        Some(lift::<T>(1.0)),
        Some(lift::<T>(2.0)),
        Some(lift::<T>(3.0)),
    ];

    match pearson_pairwise_complete(&short, &long) {
        Err(StatsError(StatsErrorEnum::DimensionMismatch(_))) => {}
        Err(StatsError(other)) => panic!("expected DimensionMismatch for 2 vs 3, got {other:?}"),
        Ok((_, n)) => panic!("expected DimensionMismatch for 2 vs 3, got Ok with count {n}"),
    }

    match pearson_pairwise_complete(&long, &short) {
        Err(StatsError(StatsErrorEnum::DimensionMismatch(_))) => {}
        Err(StatsError(other)) => panic!("expected DimensionMismatch for 3 vs 2, got {other:?}"),
        Ok((_, n)) => panic!("expected DimensionMismatch for 3 vs 2, got Ok with count {n}"),
    }
}

#[test]
fn test_pairwise_complete_length_mismatch_is_dimension_mismatch() {
    check_pairwise_length_mismatch::<f32>();
    check_pairwise_length_mismatch::<f64>();
    check_pairwise_length_mismatch::<Float106>();
}

// ---------------------------------------------------------------------------------------------
// The pair-count floor
// ---------------------------------------------------------------------------------------------

/// Two pairs is the smallest sample a correlation is defined on, and it succeeds.
///
/// The guard is `len < 2`. Only a two-pair sample separates it from `len <= 2`: with three pairs
/// both admit, with one both refuse. Two pairs always correlate perfectly — the line through them
/// is exact — so the answer is ±1 and not merely "some value".
#[test]
fn test_two_pairs_are_enough_and_correlate_perfectly() {
    let (r, n) = expect_ok(pearson(&[1.0_f64, 2.0], &[3.0, 5.0]), "two ascending pairs");
    assert_eq!(n, 2, "both pairs counted");
    assert_close(
        r,
        1.0_f64,
        F64.native,
        "two ascending points lie on a rising line",
    );

    let (r, n) = expect_ok(
        pearson(&[1.0_f64, 2.0], &[5.0, 3.0]),
        "two descending pairs",
    );
    assert_eq!(n, 2, "both pairs counted");
    assert_close(
        r,
        -1.0_f64,
        F64.native,
        "two descending points lie on a falling line",
    );
}

/// One pair is refused, which is the other side of the same threshold.
#[test]
fn test_one_pair_is_refused() {
    match pearson(&[1.0_f64], &[3.0]) {
        Err(StatsError(StatsErrorEnum::InsufficientSamples(_))) => {}
        other => panic!("one pair has no dispersion to relate, got {other:?}"),
    }
}

/// The correlation is computed in the caller's scalar, so a wider scalar buys more correct digits.
///
/// This is the property the migration was for. mRMR's Pearson accumulated in `f64` behind a
/// generic signature, so a `Float106` caller got `f64` accuracy and no way to tell. The shipped
/// `pearson` accumulates in `T`, and this measures the difference against an oracle neither
/// precision can reach.
///
/// The oracle is exact. For `x = (1, 2, 3, 4, 5)` and `y = (2, 4, 7, 8, 9)` the centred sums are
/// `Sxy = 18`, `Sxx = 10`, `Syy = 34` over the rationals, so `r² = 324/340 = 81/85` **exactly** and
/// `r = √(81/85)`. Evaluated to sixty decimal places that is
/// `0.976187060183952774000240806304295746061426416923555012612586`, which is thirty digits beyond
/// what `f64` can hold and comfortably past `Float106`'s thirty-two.
#[test]
fn test_pearson_carries_the_callers_precision() {
    const X: [f64; 5] = [1.0, 2.0, 3.0, 4.0, 5.0];
    const Y: [f64; 5] = [2.0, 4.0, 7.0, 8.0, 9.0];
    // The first thirty-four digits of √(81/85), which bracket both precisions.
    const EXACT: &str = "0.9761870601839527740002408063042957";

    let (r64, _) = pearson(&lift_array::<f64>(&X), &lift_array::<f64>(&Y)).expect("a clean pair");
    let (r106, _) =
        pearson(&lift_array::<Float106>(&X), &lift_array::<Float106>(&Y)).expect("a clean pair");

    // Agreement with the oracle, measured as the number of leading decimal digits that match.
    fn matching_digits(value: &str, exact: &str) -> usize {
        value
            .chars()
            .zip(exact.chars())
            .take_while(|(a, b)| a == b)
            .filter(|(a, _)| a.is_ascii_digit())
            .count()
    }

    let digits_64 = matching_digits(&format!("{r64:.34}"), EXACT);
    let digits_106 = matching_digits(&format!("{:.34}", r106.to_f64()), EXACT);

    // `f64` cannot do better than its own ~16 significant digits.
    assert!(
        digits_64 >= 15,
        "f64 should reach about sixteen digits, matched {digits_64}"
    );

    // The wide computation, read back at `f64`, must be at least as good — the point being that the
    // accumulation happened in `Float106`, so the error is the *conversion's*, not the algorithm's.
    assert!(
        digits_106 >= digits_64,
        "the Float106 accumulation must not be worse than the f64 one: {digits_106} vs {digits_64}"
    );

    // And the square is exact rationally, so `r²·85` is 81 to within the working precision.
    let eighty_five = lift::<Float106>(85.0);
    let eighty_one = lift::<Float106>(81.0);
    let residual = Real::abs(r106 * r106 * eighty_five - eighty_one);
    assert!(
        residual <= lift::<Float106>(F106.native),
        "r² = 81/85 exactly, so r²·85 − 81 should vanish at Float106: {residual:?}"
    );
}
