#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
"""Exact ridge solutions for the pivoting fixture in `ridge_tests.rs`.

Derives the answer from the definition — `(XᵀX + λI)⁻¹Xᵀy` — by Gaussian elimination over
`fractions.Fraction`, so the result is exact rather than floating point and shares no code with
the Rust under test. Also reports how many partial-pivot row swaps the elimination performs, which
is what makes this fixture worth having: the smaller ridge fixtures need none, so nothing exercised
the swap branch.

Run: python3 ridge_pivoting.py
"""

from fractions import Fraction as F

# Six rows, four columns. Chosen so the normal matrix needs a row swap at the first column.
X = [[1, 2, 0, 1], [0, 1, 3, 1], [2, 0, 1, 4], [1, 1, 1, 1], [3, 1, 0, 2], [0, 2, 2, 0]]
BETA = [2, -1, 3, -2]
Y = [sum(F(a) * F(b) for a, b in zip(row, BETA)) for row in X]

P, N = 4, len(X)


def solve(lam):
    """`(XᵀX + λI)β = Xᵀy`, exactly, returning (row swaps, β)."""
    a = [
        [
            sum(F(X[i][r]) * F(X[i][c]) for i in range(N)) + (F(lam) if r == c else 0)
            for c in range(P)
        ]
        for r in range(P)
    ]
    b = [sum(F(X[i][r]) * Y[i] for i in range(N)) for r in range(P)]
    m = [row[:] + [b[i]] for i, row in enumerate(a)]

    swaps = 0
    for col in range(P):
        pivot = max(range(col, P), key=lambda r: abs(m[r][col]))
        if pivot != col:
            swaps += 1
            m[col], m[pivot] = m[pivot], m[col]
        for row in range(col + 1, P):
            f = m[row][col] / m[col][col]
            for k in range(col, P + 1):
                m[row][k] -= f * m[col][k]

    out = [F(0)] * P
    for col in reversed(range(P)):
        acc = m[col][P] - sum(m[col][k] * out[k] for k in range(col + 1, P))
        out[col] = acc / m[col][col]
    return swaps, out


if __name__ == "__main__":
    print(f"X = {X}")
    print(f"y = {[int(v) for v in Y]}   (generated by beta = {BETA})")
    for lam in (0, 1, 4):
        swaps, beta = solve(lam)
        exact = ", ".join(str(v) for v in beta)
        approx = ", ".join(f"{float(v):.15f}" for v in beta)
        print(f"\nlambda = {lam}: {swaps} pivot swap(s)")
        print(f"  exact   {exact}")
        print(f"  decimal {approx}")


# -------------------------------------------------------------------------------------------------
# Fixtures the answer depends on.
#
# The fixture above makes the elimination swap rows, but it does not make the ANSWER depend on the
# swap: its diagonal is intact, and Gaussian elimination reaches the same coefficients through any
# non-zero pivot — a worse-conditioned route, not a wrong one. Mutation testing showed that
# directly: eleven mutants in the pivot search and the swap survived the whole ridge suite.
#
# For a non-negative penalty no fixture can do better. `XᵀX + λI` is then positive semi-definite,
# where `|a_ij|² ≤ a_ii · a_jj` forces a zero on the diagonal to carry a zero column with it, so a
# pivot that must be moved cannot arise. A NEGATIVE penalty is not bound by that, and the crate
# accepts one: it subtracts from the diagonal while the off-diagonal stands. Emptying a diagonal
# entry that way makes the unswapped route divide by zero and report `RankDeficient`, so the swap
# becomes load-bearing for the result.
# -------------------------------------------------------------------------------------------------


def solve_general(x, y, lam):
    """As `solve`, over an arbitrary design. Returns (swapped columns, β, σ²)."""
    n, p = len(x), len(x[0])
    a = [
        [
            sum(F(x[i][r]) * F(x[i][c]) for i in range(n)) + (F(lam) if r == c else 0)
            for c in range(p)
        ]
        for r in range(p)
    ]
    b = [sum(F(x[i][r]) * F(y[i]) for i in range(n)) for r in range(p)]
    m = [row[:] + [b[i]] for i, row in enumerate(a)]

    swapped = []
    for col in range(p):
        pivot = max(range(col, p), key=lambda r: abs(m[r][col]))
        if m[pivot][col] == 0:
            return None
        if pivot != col:
            swapped.append(col)
            m[col], m[pivot] = m[pivot], m[col]
        for row in range(col + 1, p):
            f = m[row][col] / m[col][col]
            for k in range(col, p + 1):
                m[row][k] -= f * m[col][k]

    beta = [F(0)] * p
    for col in reversed(range(p)):
        beta[col] = (m[col][p] - sum(m[col][k] * beta[k] for k in range(col + 1, p))) / m[col][col]
    rss = sum((F(y[i]) - sum(F(x[i][j]) * beta[j] for j in range(p))) ** 2 for i in range(n))
    return a, swapped, beta, rss / max(n - p, 1)


def dyadic(f):
    """Exactly representable in binary, so an `f64` literal of it is not itself an error term."""
    return f.denominator & (f.denominator - 1) == 0


SWAP_FIXTURES = [
    # The swap at column 0. β = (3/4, 1/2) and σ² = 17/16 are all dyadic, so the assertion holds at
    # the tight `solve` tolerance at every precision.
    ("column 0", [[1, 2], [0, 1], [0, 1]], [1, 1, 1], -1),
    # The swap one column in, where `row * n + col` can be told from `row * n - col`. The response is
    # scaled by 40 so β = (20, -7, 18) lands on exact integers: the natural response gives
    # β = (1/2, -7/40, 9/20), and fortieths carried as `f64` literals are already wrong by ~1e-18,
    # which is visible against Float106's tolerance and would make the test a claim about the
    # literal rather than about the solve.
    ("column 1", [[2, 1, 0], [0, 0, 1], [0, 0, 1], [1, 0, 3]], [40, 80, 40, 40], -1),
]


if __name__ == "__main__":
    for name, x, y, lam in SWAP_FIXTURES:
        a, swapped, beta, s2 = solve_general(x, y, lam)
        print(f"\n--- swap at {name}:  X = {x}, y = {y}, lambda = {lam}")
        print(f"  normal matrix  {[[str(v) for v in row] for row in a]}")
        print(f"  diagonal       {[str(a[i][i]) for i in range(len(a))]}  (a zero must be moved)")
        print(f"  columns swapped{swapped}")
        print(f"  beta           {[str(v) for v in beta]}  = {[float(v) for v in beta]}")
        print(f"  sigma2         {s2} = {float(s2)}")
        print(f"  all dyadic     {all(dyadic(v) for v in beta)}")


# -------------------------------------------------------------------------------------------------
# The four-column fixture, and the mutants it exists to kill.
#
# The two-column fixture above leaves three index mutations in the pivot search alive, for two
# geometric reasons. Its swap is at column 1 of a 3x3, where the mutated read `row * n - col` is
# 2*3 - 1 = 5 and the transpose `col * n + row` is 1*3 + 2 = 5 — the same slot; the Schur complement
# of a symmetric matrix is symmetric, so the mutant reads the transpose and finds the same number.
# And its column-1 pivot is zero only BEFORE column 0 is eliminated; afterwards it is -1, so a
# search that lands elsewhere still divides by something non-zero and reaches the same answer.
#
# Four columns break the first coincidence. This design breaks the second: after eliminating
# column 0, column 1 reads (0, 1, 0) from the diagonal down, so the only pivot in the column is two
# rows away and anything that fails to reach it divides by zero.
#
# `simulate` runs the search under each mutated index in exact arithmetic, which is what makes this
# a prediction rather than a description: the fixture was accepted only because the three mutants
# return RankDeficient here before the Rust test was written.
# -------------------------------------------------------------------------------------------------

REACH_X = [[-2, 0, -1, -1], [2, -1, -2, -1], [3, -1, 2, -2], [2, -2, 1, 3], [3, 0, 1, 3]]
REACH_Y = [-6, -6, -6, 0, -3]
REACH_LAMBDA = -3

# (label, index into `a` for the candidate row, index for the incumbent pivot)
PIVOT_READS = {
    "true index": lambda r, c, pv, n: (r * n + c, pv * n + c),
    "replace + with - in `row * n + col`": lambda r, c, pv, n: (r * n - c, pv * n + c),
    "replace + with - in `pivot * n + col`": lambda r, c, pv, n: (r * n + c, pv * n - c),
    "replace * with / in `pivot * n + col`": lambda r, c, pv, n: (r * n + c, pv // n + c),
}


def simulate(x, y, lam, read):
    """`solve_symmetric` over exact fractions, with the pivot-search read supplied by `read`."""
    rows, n = len(x), len(x[0])
    grid = [
        [
            sum(F(x[i][r]) * F(x[i][c]) for i in range(rows)) + (F(lam) if r == c else 0)
            for c in range(n)
        ]
        for r in range(n)
    ]
    a = [grid[r][c] for r in range(n) for c in range(n)]  # row-major, as in the Rust
    b = [sum(F(x[i][r]) * F(y[i]) for i in range(rows)) for r in range(n)]

    for col in range(n):
        pivot = col
        for row in range(col + 1, n):
            cand, held = read(row, col, pivot, n)
            if abs(a[cand]) > abs(a[held]):
                pivot = row
        if abs(a[pivot * n + col]) <= 0:
            return "RankDeficient"
        if pivot != col:
            for k in range(n):
                a[pivot * n + k], a[col * n + k] = a[col * n + k], a[pivot * n + k]
            b[pivot], b[col] = b[col], b[pivot]
        d = a[col * n + col]
        for row in range(col + 1, n):
            f = a[row * n + col] / d
            if f == 0:
                continue
            for k in range(col, n):
                a[row * n + k] -= f * a[col * n + k]
            b[row] -= f * b[col]

    out = [F(0)] * n
    for col in reversed(range(n)):
        out[col] = (b[col] - sum(a[col * n + k] * out[k] for k in range(col + 1, n))) / a[
            col * n + col
        ]
    return [str(v) for v in out]


if __name__ == "__main__":
    print(f"\n--- reaching fixture: X = {REACH_X}, y = {REACH_Y}, lambda = {REACH_LAMBDA}")
    for label, read in PIVOT_READS.items():
        got = simulate(REACH_X, REACH_Y, REACH_LAMBDA, read)
        print(f"  {label:38s} -> {got}")


# -------------------------------------------------------------------------------------------------
# Postscript: the solver these fixtures were built against no longer exists.
#
# `solve_symmetric` was a local Gaussian elimination inside `deep_causality_stats`. It was deleted
# once `cargo machete` showed that writing it had left the crate's declared `deep_causality_linear`
# dependency unused — which contradicted both the tier-4 SHALL in `statistics-crate-identity` and
# this change's own site inventory, where the ridge solve is described as "a substitution, not a
# re-export". Ridge and the logistic Newton step now both call `deep_causality_linear::solve`.
#
# The fixtures outlived it, and this file is still the thing that justifies them. A design whose
# only pivot is two rows below the diagonal is worth holding against whatever factorisation ridge
# delegates to, and `simulate` remains the way to check that the exact answer above is the answer,
# independently of any Rust. What the mis-addressed indices now describe is a class of solver bug
# rather than three specific mutants in code this crate owns.
# -------------------------------------------------------------------------------------------------
