[package]
name = "physics_examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false


[lib]
path = "no_lib.rs"


[dependencies]
deep_causality = { workspace = true }
deep_causality_core = { workspace = true, features = ["default"] }
deep_causality_calculus = { workspace = true, features = ["default"] }
deep_causality_physics = { workspace = true, features = ["default", "os-random"] }
deep_causality_quantum = { workspace = true }
deep_causality_multivector = { workspace = true, features = ["default"] }
deep_causality_tensor = { workspace = true, features = ["default"] }
deep_causality_topology = { workspace = true }
deep_causality_num = { workspace = true, features = ["default"] }
deep_causality_num_complex = { workspace = true, features = ["default"] }
deep_causality_num_dual = { workspace = true, features = ["default"] }
deep_causality_algebra = { workspace = true, features = ["default"] }
deep_causality_linear = { workspace = true, features = ["default"] }
deep_causality_rand = { workspace = true, features = ["os-random"] }

[[example]]
name = "bernoulli_flow_network"
path = "bernoulli_flow_network/main.rs"

[[example]]
name = "carnot_cycle_engine"
path = "carnot_cycle_engine/main.rs"

[[example]]
name = "event_horizon_probe"
path = "event_horizon_probe/main.rs"

[[example]]
name = "gauge_gr"
path = "gauge_gr/main.rs"

[[example]]
name = "gauge_lattice_u1_2d"
path = "gauge_lattice_u1_2d/main.rs"

[[example]]
name = "gauge_em"
path = "gauge_em/main.rs"

[[example]]
name = "gauge_weak_force"
path = "gauge_weak_force/main.rs"

[[example]]
name = "geometric_tilt"
path = "geometric_tilt/main.rs"

[[example]]
name = "gravitational_wave"
path = "gravitational_wave/main.rs"

[[example]]
name = "grmhd_example"
path = "grmhd/main.rs"

[[example]]
name = "laser_resonator_stability"
path = "laser_resonator_stability/main.rs"

[[example]]
name = "maxwell_example"
path = "maxwell/main.rs"

[[example]]
name = "multi_physics_pipeline"
path = "multi_physics_pipeline/main.rs"


[lints]
workspace = true
