[package]
name = "example-starter"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deep_causality = { path = "../../deep_causality" }
