# SPDX-License-Identifier: MIT
# Copyright (c) "2025" . The DeepCausality Authors and Contributors. All Rights Reserved.

[package]
name = "example-starter"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false


[dependencies]
deep_causality = { path = "../../deep_causality" }
