load("@crates//:defs.bzl", "aliases", "all_crate_deps", "lint_config")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_test_suite")

rust_library(
    name = "deep_causality_num_complex",
    srcs = glob([
        "src/**",
    ]),
    aliases = aliases(),
    crate_root = "src/lib.rs",
    lint_config = lint_config(),
    tags = [
        "complex",
        "math",
    ],
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_doc(
    name = "doc",
    crate = ":deep_causality_num_complex",
    tags = ["doc"],
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    crate = ":deep_causality_num_complex",
    tags = ["doc-test"],
    visibility = ["//visibility:public"],
)

rust_test_suite(
    name = "extensions",
    srcs = glob([
        "tests/extensions/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_num_complex",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "complex",
    srcs = glob([
        "tests/complex/complex_number/*_tests.rs",
        "tests/complex/octonion_number/*_tests.rs",
        "tests/complex/quaternion_number/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_num_complex",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "formalization_lean",
    srcs = glob([
        "tests/formalization_lean/*_tests.rs",
    ]),
    tags = [
        "lean-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_num_complex",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "algebra_impls",
    srcs = glob([
        "tests/algebra_impls/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_num_complex",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "hom",
    srcs = glob([
        "tests/hom/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_num_complex",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
