[package]
name = "deep_causality_num_complex"
version = "0.1.7"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

repository = "https://github.com/deepcausality/deep_causality.rs"
authors = ["Marvin Hansen <marvin.hansen@gmail.com>", ]
description = "Complex, quaternion, and octonion number types for deep_causality."
documentation = "https://docs.rs/deep_causality_num_complex"
categories = ["development-tools", "mathematics"]
keywords = ["complex", "quaternion", "octonion", "numbers"]
# Exclude all bazel files as these conflict with Bazel workspace when vendored.
exclude = [
    "*.bazel",
    "*/*.bazel",
    "*.bazel.*",
    "BUILD",
    "BUILD.bazel",
    "MODULE.bazel",
    ".bazelignore",
    ".bazelrc",
    "tests/*",
    "tests/**/*",
    "papers/*",
]

[features]
default = ["std"]
std = ["deep_causality_num/std", "deep_causality_algebra/std", "deep_causality_haft/std"]
no-std = ["deep_causality_num/no-std", "deep_causality_algebra/no-std", "deep_causality_haft/no-std"]

[dependencies.deep_causality_num]
workspace = true

[dependencies.deep_causality_haft]
workspace = true

[dependencies.deep_causality_algebra]
workspace = true

[lints]
workspace = true
