[package]
name = "tensor_impl"
version = "0.0.0"
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[features]
default = []
orphan_probe = []

[dependencies]
linear_b = { path = "../linear_b" }
deep_causality_tensor = { workspace = true }
deep_causality_sparse = { workspace = true }
deep_causality_num = { workspace = true }
deep_causality_algebra = { workspace = true }

[lints]
workspace = true
