#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
#
# Regenerate lean/lake-lock.json — the content-addressed pin for the Lean/Mathlib
# workspace.
#
# WHY THIS EXISTS
#
# Without a lock, @lake_deps is built at fetch time by `lake update` (nine full git
# clones) and `lake exe cache get` (one blob per mathlib module). Neither runs
# through Bazel's downloader, so neither is covered by --repository_cache or
# --experimental_remote_downloader, and the result is not byte-reproducible. Every
# cold output base re-fetches the lot; CI pays it on every run.
#
# The lock pins each package to a sha256-addressed archive, so fetching becomes
# `download_and_extract` and nothing else. This script is the repin step — the
# analogue of `bazel run //thirdparty:crates_vendor`. Its output is committed and
# reviewed; nothing resolves at fetch time.
#
# USAGE
#
#   scripts/lean_lock.sh sources
#       Re-pin the nine package source archives from lean/lake-manifest.json.
#       Downloads each tarball once to hash it. Needs no hosting.
#
#   scripts/lean_lock.sh oleans <URL>
#       Pack the prebuilt olean trees out of an already-materialized @lake_deps,
#       hash the tarball, and record it in the lock under the URL you will serve
#       it from. Run `bazel build //lean/...` once (legacy path) to materialize
#       the oleans before calling this.
#
# The rule validates the lock against lake-manifest.json and lean-toolchain on
# every fetch and fails closed on drift, so a forgotten repin is an error, never
# a silent mismatch.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="${REPO_ROOT}/lean/lake-manifest.json"
TOOLCHAIN="${REPO_ROOT}/lean/lean-toolchain"
LOCK="${REPO_ROOT}/lean/lake-lock.json"
WORK="${TMPDIR:-/tmp}/lean_lock.$$"

die() {
    echo "lean_lock: $*" >&2
    exit 1
}

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d' ' -f1
    else
        shasum -a 256 "$1" | cut -d' ' -f1
    fi
}

# ── sources ──────────────────────────────────────────────────────────────────
# GitHub serves an immutable tarball per commit at
#   https://github.com/<org>/<repo>/archive/<rev>.tar.gz
# which extracts to `<repo>-<rev>/`. Those are the archives the lock pins; the
# revs come from lake-manifest.json, so the lock can never point at a different
# commit than Lake resolved.
cmd_sources() {
    [ -f "${MANIFEST}" ] || die "no manifest at ${MANIFEST}"
    mkdir -p "${WORK}"
    trap 'rm -rf "${WORK}"' EXIT

    local lean_toolchain
    lean_toolchain="$(head -n1 "${TOOLCHAIN}" | tr -d '[:space:]')"

    # Preserve any existing olean pin: re-pinning sources must not silently drop
    # the archive that makes the fast path work.
    local prior_oleans='{}'
    if [ -f "${LOCK}" ]; then
        prior_oleans="$(python3 -c '
import json,sys
print(json.dumps(json.load(open(sys.argv[1])).get("oleans", {})))
' "${LOCK}")"
    fi

    echo "lean_lock: hashing package archives from ${MANIFEST}" >&2

    # Derive the archive URLs from the manifest, then hash each one with curl +
    # sha256. curl rather than Python's urllib: the interpreter on a dev machine
    # may have no CA bundle, and a repin must not depend on that.
    python3 - "${MANIFEST}" > "${WORK}/pkgs.tsv" <<'PY'
import json, sys
manifest = json.load(open(sys.argv[1]))
for pkg in manifest["packages"]:
    url = pkg["url"].removesuffix(".git")
    rev = pkg["rev"]
    repo = url.rsplit("/", 1)[-1]
    # GitHub's archive endpoint is immutable per commit and always roots the
    # tarball at <repo>-<rev>/.
    print("\t".join([pkg["name"], rev, f"{url}/archive/{rev}.tar.gz", f"{repo}-{rev}"]))
PY

    : > "${WORK}/hashed.tsv"
    while IFS=$'\t' read -r name rev archive prefix; do
        printf '  %-18s %s\n' "${name}" "${archive}" >&2
        curl -fsSL --retry 3 --retry-delay 2 -o "${WORK}/pkg.tar.gz" "${archive}" \
            || die "failed to download ${archive}"
        printf '%s\t%s\t%s\t%s\t%s\n' \
            "${name}" "${rev}" "${archive}" "$(sha256_of "${WORK}/pkg.tar.gz")" "${prefix}" \
            >> "${WORK}/hashed.tsv"
    done < "${WORK}/pkgs.tsv"

    python3 - "${WORK}/hashed.tsv" "${lean_toolchain}" "${prior_oleans}" "${LOCK}" <<'PY'
import json, sys

hashed_path, lean_toolchain, prior_oleans, lock_path = sys.argv[1:5]

packages = []
for line in open(hashed_path):
    name, rev, url, sha, prefix = line.rstrip("\n").split("\t")
    packages.append({
        "name": name,
        "rev": rev,
        "url": url,
        "sha256": sha,
        "strip_prefix": prefix,
    })

lock = {
    "version": 1,
    "_comment": (
        "Generated by scripts/lean_lock.sh -- do not hand-edit. Pins the Lean "
        "workspace to sha256-addressed archives so @lake_deps is fetched with "
        "download_and_extract instead of git clone + lake exe cache get. Regenerate "
        "after any change to lean/lake-manifest.json or lean/lean-toolchain."
    ),
    "lean_toolchain": lean_toolchain,
    "packages": packages,
    "oleans": json.loads(prior_oleans),
}

with open(lock_path, "w") as f:
    json.dump(lock, f, indent=2, sort_keys=False)
    f.write("\n")
print(f"lean_lock: wrote {lock_path} ({len(packages)} packages)", file=sys.stderr)
PY

    # Both derive from the manifest, so they are regenerated together.
    cmd_packages

    if [ "${prior_oleans}" = "{}" ]; then
        cat >&2 <<'EOF'

lean_lock: no olean archive pinned yet, so the fast path stays OFF and the rule
           keeps using `lake update` + `cache get`. That is deliberate: mathlib's
           cache client reads mathlib/.git, so tarball-sourced packages cannot
           fall back to it. Pin the oleans to turn the fast path on:

             bazel build //lean/...                       # materialize once (legacy path)
             scripts/lean_lock.sh oleans <URL>      # pack, hash, record
EOF
    fi
}

# ── oleans ───────────────────────────────────────────────────────────────────
# Packs every package's `.lake/build` tree out of a materialized @lake_deps. The
# archive is rooted at `.lake/packages`, i.e. entries look like
# `mathlib/.lake/build/lib/lean/...`, which is what the rule extracts over the
# freshly fetched sources.
cmd_oleans() {
    local url="${1:-}"
    [ -n "${url}" ] || die "usage: lean_lock.sh oleans <URL the archive will be served from> [output-path]"
    [ -f "${LOCK}" ] || die "no lock at ${LOCK}; run \`lean_lock.sh sources\` first"

    # Source workspace: prefer the standalone Lake build in lean/, fall back to the
    # one Bazel materialized. Either is a full `.lake/packages` tree.
    local packages_dir="${REPO_ROOT}/lean/.lake/packages"
    if [ ! -d "${packages_dir}" ]; then
        packages_dir="$(cd "${REPO_ROOT}" && bazel info output_base)/external/rules_lean++lake+lake_deps/lake_ws/.lake/packages"
    fi
    [ -d "${packages_dir}" ] || die "no materialized workspace found.
Run \`lake build\` in lean/, or \`bazel build //lean/...\` with the fast path off."

    mkdir -p "${WORK}"
    trap 'rm -rf "${WORK}"' EXIT

    # NOT under ${WORK}: the archive is this command's deliverable and must survive
    # the cleanup trap. Second arg overrides the destination.
    local tarball="${2:-${TMPDIR:-/tmp}/lake-oleans-$(head -n1 "${TOOLCHAIN}" | tr -d '[:space:]' | tr '/:' '--').tar.gz}"
    mkdir -p "$(dirname "${tarball}")"
    echo "lean_lock: packing ${packages_dir}" >&2

    # Tree-shaken to the proofs' import closure, and build trees only: sources come
    # from the pinned package archives, and `.git` must not appear here at all --
    # non-reproducible packfiles are what this whole change exists to remove.
    ( cd "${REPO_ROOT}" && python3 scripts/lean_oleans.py "${packages_dir}" "${tarball}" ) \
        || die "packing failed"

    local digest size
    digest="$(sha256_of "${tarball}")"
    size="$(du -h "${tarball}" | cut -f1)"

    # Record WHAT the archive was cut from, not just the archive. `inputs_sha256`
    # digests the direct imports plus the pinned package revs -- the two inputs the
    # closure depends on -- so `lean_lock.sh check` can tell a stale archive from a
    # current one without Lean, a workspace, or the network.
    local inputs
    inputs="$(cd "${REPO_ROOT}" && python3 scripts/lean_closure.py fingerprint)"

    python3 - "${LOCK}" "${url}" "${digest}" "${inputs}" <<'PY'
import json, sys
lock_path, url, sha, inputs = sys.argv[1:5]
meta = json.loads(inputs)
lock = json.load(open(lock_path))
lock["oleans"] = {
    "url": url,
    "sha256": sha,
    "strip_prefix": "",
    "inputs_sha256": meta["inputs_sha256"],
    "imports": meta["imports"],
}
with open(lock_path, "w") as f:
    json.dump(lock, f, indent=2, sort_keys=False)
    f.write("\n")
PY

    cat >&2 <<EOF

lean_lock: archive ready
  file:   ${tarball}
  size:   ${size}
  sha256: ${digest}
  url:    ${url}   (recorded in ${LOCK})

Upload the archive to that URL, then \`bazel build //lean/...\` takes the
content-addressed path. Keep the file immutable: the sha256 in the lock is the
only thing standing between a swapped artifact and a silently different proof
check. GitHub Release assets cap at 2 GB per file; object storage (R2/S3) has no
such limit and is the safer home for a multi-GB olean tree.
EOF
}

# ── packages ─────────────────────────────────────────────────────────────────
# Emit lean/lake_packages.bzl: the @lake_deps package labels, as a LOCAL file.
#
# lean/BUILD.bazel used to `load("@lake_deps//:packages.bzl", ...)`. A load() from
# an external repo forces that repo to be FETCHED before the loading package can be
# evaluated, and `bazel build //...` evaluates every package -- so building a Rust
# crate pulled in the whole Lake/Mathlib workspace. Generating the list here keeps
# @lake_deps out of the loading phase; the labels are plain attribute values, which
# Bazel resolves lazily, only for targets it actually analyzes.
cmd_packages() {
    [ -f "${MANIFEST}" ] || die "no manifest at ${MANIFEST}"
    # A materialized workspace decides which manifest packages actually build to
    # oleans; rules_lean emits targets only for those. Prefer the standalone Lake
    # workspace in lean/, fall back to the one Bazel materialized.
    local pkgs="${REPO_ROOT}/lean/.lake/packages"
    if [ ! -d "${pkgs}" ]; then
        pkgs="$(cd "${REPO_ROOT}" && bazel info output_base)/external/rules_lean++lake+lake_deps/lake_ws/.lake/packages"
    fi
    python3 "${REPO_ROOT}/scripts/lean_packages_bzl.py" \
        "${MANIFEST}" "${REPO_ROOT}/lean/lake_packages.bzl" "${pkgs}"
}

# ── check ────────────────────────────────────────────────────────────────────
# Fail when the tree-shaken artifacts no longer cover what the proofs import.
# Needs no Lean toolchain, no Lake workspace and no network -- see lean_closure.py.
cmd_check() {
    ( cd "${REPO_ROOT}" && python3 scripts/lean_closure.py check )
}

case "${1:-}" in
    sources)  shift; cmd_sources "$@" ;;
    packages) shift; cmd_packages "$@" ;;
    oleans)   shift; cmd_oleans "$@" ;;
    check)    shift; cmd_check "$@" ;;
    *) die "usage: lean_lock.sh {sources|packages|oleans <URL> [out]|check}" ;;
esac
