#!/usr/bin/env python3
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
#
# Generate lean/lake_packages.bzl from lean/lake-manifest.json.
#
# Invoked by scripts/lean_lock.sh; kept as its own file because the generated
# content is full of quotes and heredoc-hostile text.
#
# The manifest is NOT the whole story. rules_lean emits a `lean_prebuilt_library`
# only for packages that actually carry oleans (`_write_package_markers` skips the
# rest), so a package listed in the manifest but built to nothing -- `Cli` at the
# pinned revs -- has no target in @lake_deps. Listing it here produces
# "//lean:X depends on @lake_deps//:Cli" at analysis time. So the manifest supplies
# the names and their casing, and a materialized workspace decides which survive.

import json
import os
import sys

HEADER = '''"""Generated by scripts/lean_lock.sh -- do not hand-edit.

The Lake packages that @lake_deps exposes as targets.

This list is generated LOCALLY rather than loaded from `@lake_deps//:packages.bzl`
on purpose. A `load()` from an external repo forces that repo to be FETCHED before
the loading package can be evaluated, and `bazel build //...` evaluates every
package -- so loading the list from @lake_deps made a full Lake/Mathlib fetch the
price of building any target in the workspace, including pure-Rust ones and
including invocations that explicitly exclude //lean/....

As plain label strings the deps stay lazy: Bazel resolves them only for targets it
actually analyzes, so @lake_deps is fetched when, and only when, a //lean target is
being built.

The list is the manifest packages that BUILD to oleans, not every manifest package:
rules_lean emits a target only for packages with a non-empty olean tree.
%s

Regenerate with `scripts/lean_lock.sh packages` after changing
lean/lake-manifest.json.
"""

LAKE_PACKAGES = [
'''


def main() -> int:
    manifest_path, out_path, packages_dir = sys.argv[1], sys.argv[2], sys.argv[3]

    if not os.path.isdir(packages_dir):
        print(
            "lean_packages: no materialized workspace at %s -- cannot tell which packages\n"
            "               build to oleans. Run `bazel build //lean/...` or the standalone\n"
            "               `lake build` in lean/ first." % packages_dir,
            file=sys.stderr,
        )
        return 1

    names = [p["name"] for p in json.load(open(manifest_path))["packages"]]
    kept, dropped = [], []
    for name in names:
        lib = os.path.join(packages_dir, name, ".lake", "build", "lib", "lean")
        has = any(
            f.endswith(".olean")
            for _, _, files in os.walk(lib)
            for f in files
        ) if os.path.isdir(lib) else False
        (kept if has else dropped).append(name)

    note = (
        "Excluded because they build to no oleans at the pinned revs: %s."
        % ", ".join("`%s`" % d for d in dropped)
    ) if dropped else "Every manifest package builds to oleans at the pinned revs."

    with open(out_path, "w") as f:
        f.write(HEADER % note)
        for name in kept:
            f.write('    "@lake_deps//:%s",\n' % name)
        f.write("]\n")

    print(
        "lean_lock: wrote %s (%d packages%s)"
        % (out_path, len(kept), ", excluded %s" % ", ".join(dropped) if dropped else ""),
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
