load("@crates//:defs.bzl", "aliases", "all_crate_deps", "lint_config")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_test_suite")

rust_library(
    name = "deep_causality_core",
    srcs = glob([
        "src/**",
    ]),
    aliases = aliases(),
    crate_features = [
        "std",
        "alloc",
    ],  #
    crate_root = "src/lib.rs",
    lint_config = lint_config(),
    tags = [
        "deep_causality_core",
    ],
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_doc(
    name = "doc",
    crate = ":deep_causality_core",
    crate_features = [
        "std",
        "alloc",
    ],
    tags = ["doc"],
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    crate = ":deep_causality_core",
    crate_features = [
        "std",
        "alloc",
    ],
    tags = ["doc-test"],
    visibility = ["//visibility:public"],
)

rust_test_suite(
    name = "errors",
    srcs = glob([
        "tests/errors/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "formalization_lean",
    srcs = glob([
        "tests/formalization_lean/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "iso",
    srcs = glob([
        "tests/iso/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "traits",
    srcs = glob([
        "tests/traits/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_causal_arrow",
    srcs = glob([
        "tests/types/causal_arrow/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_causal_effect",
    srcs = glob([
        "tests/types/causal_effect/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_causal_effect_propagation_process",
    srcs = glob([
        "tests/types/causal_effect_propagation_process/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_causal_flow",
    srcs = glob([
        "tests/types/causal_flow/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_causal_monad",
    srcs = glob([
        "tests/types/causal_monad/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_effect_log",
    srcs = glob([
        "tests/types/effect_log/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_io",
    srcs = glob([
        "tests/types/io/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_propagating_effect",
    srcs = glob([
        "tests/types/propagating_effect/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_propagating_process",
    srcs = glob([
        "tests/types/propagating_process/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_core",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
