[package]
name = "causal_uncertain_examples"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "no_lib.rs"

[dependencies]
deep_causality_core = { workspace = true, features = ["default"] }
deep_causality_haft = { workspace = true, features = ["default"] }
deep_causality_uncertain = { workspace = true }

[[example]]
name = "gps_navigation"
path = "gps_navigation/main.rs"

[[example]]
name = "sensor_processing"
path = "sensor_processing/main.rs"

[[example]]
name = "clinical_trial"
path = "clinical_trial/main.rs"

[lints]
workspace = true
