load("@crates//:defs.bzl", "aliases", "all_crate_deps", "lint_config")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_test_suite")

rust_library(
    name = "deep_causality_ethos",
    srcs = glob([
        "src/**",
    ]),
    aliases = aliases(),
    crate_features = [
        "std",
    ],
    crate_root = "src/lib.rs",
    lint_config = lint_config(),
    tags = [
        "deep_causality_ethos",
    ],
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_doc(
    name = "doc",
    crate = ":deep_causality_ethos",
    tags = ["doc"],
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    crate = ":deep_causality_ethos",
    tags = ["doc-test"],
    visibility = ["//visibility:public"],
)

rust_test_suite(
    name = "errors",
    srcs = glob([
        "tests/errors/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_tag_index",
    srcs = glob([
        "tests/types/tag_index/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_effect_ethos",
    srcs = glob([
        "tests/types/effect_ethos/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_teloid",
    srcs = glob([
        "tests/types/teloid/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_teloid_graph",
    srcs = glob([
        "tests/types/teloid_graph/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_teloid_modal",
    srcs = glob([
        "tests/types/teloid_modal/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_teloid_relation",
    srcs = glob([
        "tests/types/teloid_relation/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_teloid_store",
    srcs = glob([
        "tests/types/teloid_store/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types_teloid_verdict",
    srcs = glob([
        "tests/types/teloid_verdict/*_tests.rs",
    ]),
    crate_features = [
        "std",
        "alloc",
    ],
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "utils_test",
    srcs = glob([
        "tests/utils_test/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_ethos",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
