# SPDX-License-Identifier: MIT
# Copyright (c) "2025" . The DeepCausality Authors and Contributors. All Rights Reserved.

[package]
name = "example-dbn"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
publish = false

[dependencies]
deep_causality = { path = "../../deep_causality" }
rand = "0.9"
