"""Generated by build/scripts/lean_lock.sh -- do not hand-edit.

The Lake packages that @lake_deps exposes as targets.

This list is generated LOCALLY rather than loaded from `@lake_deps//:packages.bzl`
on purpose. A `load()` from an external repo forces that repo to be FETCHED before
the loading package can be evaluated, and `bazel build //...` evaluates every
package -- so loading the list from @lake_deps made a full Lake/Mathlib fetch the
price of building any target in the workspace, including pure-Rust ones and
including invocations that explicitly exclude //lean/....

As plain label strings the deps stay lazy: Bazel resolves them only for targets it
actually analyzes, so @lake_deps is fetched when, and only when, a //lean target is
being built.

The list is the manifest packages that BUILD to oleans, not every manifest package:
rules_lean emits a target only for packages with a non-empty olean tree.
Excluded because they build to no oleans at the pinned revs: `Cli`.

Regenerate with `build/scripts/lean_lock.sh packages` after changing
lean/lake-manifest.json.
"""

LAKE_PACKAGES = [
    "@lake_deps//:mathlib",
    "@lake_deps//:plausible",
    "@lake_deps//:LeanSearchClient",
    "@lake_deps//:importGraph",
    "@lake_deps//:proofwidgets",
    "@lake_deps//:aesop",
    "@lake_deps//:Qq",
    "@lake_deps//:batteries",
]
