/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
 */

use crate::QuantumError;
use crate::types::qcode::logical_pauli::LogicalPauli;
use alloc::vec::Vec;
use deep_causality_homology::{ChainComplex, Gf2Chain};
use deep_causality_num::{Gf2, NaturalNumber};

/// The logical operators of a CSS code at one grade: a basis of `H_k` and one of `H^k`.
///
/// Haruna's Theorem A.1 with B.1 to B.3: an operator acts trivially on the code space exactly when
/// it commutes with every logical `Z̄(γ)` for `γ` in `H₁` and every `X̄(γ̃)` for `γ̃` in `H¹`. Because
/// the logical operators are generated by a basis, checking the basis checks the group, and the
/// whole test reduces to inner products over 𝔽₂.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LogicalBasis<W> {
    homology: Vec<Gf2Chain<W>>,
    cohomology: Vec<Gf2Chain<W>>,
    len: usize,
}

impl<W: NaturalNumber> LogicalBasis<W> {
    /// The logical basis of `complex` at grade `k`, over 𝔽₂.
    ///
    /// # Errors
    ///
    /// [`QuantumError::DimensionMismatch`] if the 𝔽₂ elimination underneath fails.
    pub fn from_complex<K: ChainComplex + ?Sized>(
        complex: &K,
        k: usize,
    ) -> Result<Self, QuantumError> {
        let homology = complex
            .homology_representatives::<W>(k)
            .map_err(|e| QuantumError::DimensionMismatch(alloc::format!("{e}")))?;
        let cohomology = complex
            .cohomology_representatives::<W>(k)
            .map_err(|e| QuantumError::DimensionMismatch(alloc::format!("{e}")))?;
        Ok(Self {
            homology,
            cohomology,
            len: complex.num_cells(k),
        })
    }

    /// The `H_k` representatives, the logical `Z` generators.
    pub fn homology(&self) -> &[Gf2Chain<W>] {
        &self.homology
    }

    /// The `H^k` representatives, the logical `X` generators.
    pub fn cohomology(&self) -> &[Gf2Chain<W>] {
        &self.cohomology
    }

    /// The number of encoded logical qubits, `k = dim H_k`.
    pub fn num_logical_qubits(&self) -> usize {
        self.homology.len()
    }

    /// Whether `op` acts trivially on the code space: `O ~ I`.
    ///
    /// # What is decided, and what is assumed
    ///
    /// This is B.1's criterion, which is a statement about commutation. A Pauli `P = (x, z)`
    /// anticommutes with `Z̄(γ) = ∏_{i∈γ} Z_i` exactly when `|x ∩ γ|` is odd, since a single `X_i`
    /// and `Z_i` anticommute and everything else commutes; that count mod two is `⟨x, γ⟩`.
    /// Symmetrically for `X̄(γ̃)` and `⟨z, γ̃⟩`. So `op` is trivial when both pairings vanish against
    /// every generator.
    ///
    /// **The precondition is not checked here.** The criterion decides triviality *of a logical
    /// operator*. An operator outside the code's normalizer commutes with the logical generators
    /// without acting trivially on the code space, because it leaves the code space instead. A
    /// caller passing an arbitrary Pauli gets an answer to the commutation question, which is the
    /// one this crate can ask without a stabilizer group it does not carry.
    ///
    /// # Errors
    ///
    /// [`QuantumError::DimensionMismatch`] if `op` is over a register of a different width from the
    /// complex this basis came from.
    pub fn is_logically_trivial(&self, op: &LogicalPauli<W>) -> Result<bool, QuantumError> {
        if op.len() != self.len {
            return Err(QuantumError::DimensionMismatch(alloc::format!(
                "the operator is over {} qubits, the code over {}",
                op.len(),
                self.len
            )));
        }
        for gamma in &self.homology {
            if pair(op.x(), gamma)? == Gf2::ONE {
                return Ok(false);
            }
        }
        for gamma_tilde in &self.cohomology {
            if pair(op.z(), gamma_tilde)? == Gf2::ONE {
                return Ok(false);
            }
        }
        Ok(true)
    }

    /// Whether `a` and `b` act alike on the code space: `O₁ ~ O₂`.
    ///
    /// B.1's reduction, `O₁ ~ O₂ ⟺ O₁O₂⁻¹ ~ I`. A Pauli is its own inverse up to phase, so the
    /// composite is the 𝔽₂ sum of the two symplectic vectors and the question passes to
    /// [`is_logically_trivial`](Self::is_logically_trivial).
    ///
    /// # Errors
    ///
    /// As [`is_logically_trivial`](Self::is_logically_trivial), and if the two operators are over
    /// different registers.
    pub fn are_logically_equivalent(
        &self,
        a: &LogicalPauli<W>,
        b: &LogicalPauli<W>,
    ) -> Result<bool, QuantumError> {
        self.is_logically_trivial(&a.compose(b)?)
    }
}

/// The 𝔽₂ pairing of two chains, reported as a quantum-layer error.
fn pair<W: NaturalNumber>(a: &Gf2Chain<W>, b: &Gf2Chain<W>) -> Result<Gf2, QuantumError> {
    a.inner(b)
        .map_err(|e| QuantumError::DimensionMismatch(alloc::format!("{e}")))
}
