/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) "2025" . The DeepCausality Authors and Contributors. All Rights Reserved.
 */
mod display;
mod from;

use crate::{
    BaseCausaloid, ContextoidId, IdentificationValue, MonadicCausable, NumericValue,
    PropagatingEffect,
};
use deep_causality_num::{Complex, Quaternion};
use deep_causality_tensor::CausalTensor;
use deep_causality_uncertain::{UncertainBool, UncertainF64};

/// An enum to wrap all statically-known Causaloid types.
/// This allows for static dispatch via a `match` statement.
#[derive(Debug, Clone)]
pub enum RegisteredCausaloid {
    // === START OF STATICALLY-KNOWN TYPES ===
    DeterministicToDeterministic(BaseCausaloid<bool, bool>),
    DeterministicToNumber(BaseCausaloid<bool, NumericValue>),
    DeterministicToNumerical(BaseCausaloid<bool, f64>),
    DeterministicToProbabilistic(BaseCausaloid<bool, f64>),
    DeterministicToTensor(BaseCausaloid<bool, CausalTensor<f64>>),
    DeterministicToComplex(BaseCausaloid<bool, Complex<f64>>),
    DeterministicToComplexTensor(BaseCausaloid<bool, CausalTensor<Complex<f64>>>),
    DeterministicToQuaternion(BaseCausaloid<bool, Quaternion<f64>>),
    DeterministicToQuaternionTensor(BaseCausaloid<bool, CausalTensor<Quaternion<f64>>>),
    DeterministicToUncertainBool(BaseCausaloid<bool, UncertainBool>),
    DeterministicToUncertainFloat(BaseCausaloid<bool, UncertainF64>),
    DeterministicToContextualLink(BaseCausaloid<bool, ContextoidId>),
    DeterministicToRelayTo(BaseCausaloid<bool, IdentificationValue>),
    NumberToDeterministic(BaseCausaloid<NumericValue, bool>),
    NumberToNumber(BaseCausaloid<NumericValue, NumericValue>),
    NumberToNumerical(BaseCausaloid<NumericValue, f64>),
    NumberToProbabilistic(BaseCausaloid<NumericValue, f64>),
    NumberToTensor(BaseCausaloid<NumericValue, CausalTensor<f64>>),
    NumberToComplex(BaseCausaloid<NumericValue, Complex<f64>>),
    NumberToComplexTensor(BaseCausaloid<NumericValue, CausalTensor<Complex<f64>>>),
    NumberToQuaternion(BaseCausaloid<NumericValue, Quaternion<f64>>),
    NumberToQuaternionTensor(BaseCausaloid<NumericValue, CausalTensor<Quaternion<f64>>>),
    NumberToUncertainBool(BaseCausaloid<NumericValue, UncertainBool>),
    NumberToUncertainFloat(BaseCausaloid<NumericValue, UncertainF64>),
    NumberToContextualLink(BaseCausaloid<NumericValue, ContextoidId>),
    NumberToRelayTo(BaseCausaloid<NumericValue, IdentificationValue>),
    NumericalToDeterministic(BaseCausaloid<f64, bool>),
    NumericalToNumber(BaseCausaloid<f64, NumericValue>),
    NumericalToNumerical(BaseCausaloid<f64, f64>),
    NumericalToProbabilistic(BaseCausaloid<f64, f64>),
    NumericalToTensor(BaseCausaloid<f64, CausalTensor<f64>>),
    NumericalToComplex(BaseCausaloid<f64, Complex<f64>>),
    NumericalToComplexTensor(BaseCausaloid<f64, CausalTensor<Complex<f64>>>),
    NumericalToQuaternion(BaseCausaloid<f64, Quaternion<f64>>),
    NumericalToQuaternionTensor(BaseCausaloid<f64, CausalTensor<Quaternion<f64>>>),
    NumericalToUncertainBool(BaseCausaloid<f64, UncertainBool>),
    NumericalToUncertainFloat(BaseCausaloid<f64, UncertainF64>),
    NumericalToContextualLink(BaseCausaloid<f64, ContextoidId>),
    NumericalToRelayTo(BaseCausaloid<f64, IdentificationValue>),
    ProbabilisticToDeterministic(BaseCausaloid<f64, bool>),
    ProbabilisticToNumber(BaseCausaloid<f64, NumericValue>),
    ProbabilisticToNumerical(BaseCausaloid<f64, f64>),
    ProbabilisticToProbabilistic(BaseCausaloid<f64, f64>),
    ProbabilisticToTensor(BaseCausaloid<f64, CausalTensor<f64>>),
    ProbabilisticToComplex(BaseCausaloid<f64, Complex<f64>>),
    ProbabilisticToComplexTensor(BaseCausaloid<f64, CausalTensor<Complex<f64>>>),
    ProbabilisticToQuaternion(BaseCausaloid<f64, Quaternion<f64>>),
    ProbabilisticToQuaternionTensor(BaseCausaloid<f64, CausalTensor<Quaternion<f64>>>),
    ProbabilisticToUncertainBool(BaseCausaloid<f64, UncertainBool>),
    ProbabilisticToUncertainFloat(BaseCausaloid<f64, UncertainF64>),
    ProbabilisticToContextualLink(BaseCausaloid<f64, ContextoidId>),
    ProbabilisticToRelayTo(BaseCausaloid<f64, IdentificationValue>),
    TensorToDeterministic(BaseCausaloid<CausalTensor<f64>, bool>),
    TensorToNumber(BaseCausaloid<CausalTensor<f64>, NumericValue>),
    TensorToNumerical(BaseCausaloid<CausalTensor<f64>, f64>),
    TensorToProbabilistic(BaseCausaloid<CausalTensor<f64>, f64>),
    TensorToTensor(BaseCausaloid<CausalTensor<f64>, CausalTensor<f64>>),
    TensorToComplex(BaseCausaloid<CausalTensor<f64>, Complex<f64>>),
    TensorToComplexTensor(BaseCausaloid<CausalTensor<f64>, CausalTensor<Complex<f64>>>),
    TensorToQuaternion(BaseCausaloid<CausalTensor<f64>, Quaternion<f64>>),
    TensorToQuaternionTensor(BaseCausaloid<CausalTensor<f64>, CausalTensor<Quaternion<f64>>>),
    TensorToUncertainBool(BaseCausaloid<CausalTensor<f64>, UncertainBool>),
    TensorToUncertainFloat(BaseCausaloid<CausalTensor<f64>, UncertainF64>),
    TensorToContextualLink(BaseCausaloid<CausalTensor<f64>, ContextoidId>),
    TensorToRelayTo(BaseCausaloid<CausalTensor<f64>, IdentificationValue>),
    ComplexToDeterministic(BaseCausaloid<Complex<f64>, bool>),
    ComplexToNumber(BaseCausaloid<Complex<f64>, NumericValue>),
    ComplexToNumerical(BaseCausaloid<Complex<f64>, f64>),
    ComplexToProbabilistic(BaseCausaloid<Complex<f64>, f64>),
    ComplexToTensor(BaseCausaloid<Complex<f64>, CausalTensor<f64>>),
    ComplexToComplex(BaseCausaloid<Complex<f64>, Complex<f64>>),
    ComplexToComplexTensor(BaseCausaloid<Complex<f64>, CausalTensor<Complex<f64>>>),
    ComplexToQuaternion(BaseCausaloid<Complex<f64>, Quaternion<f64>>),
    ComplexToQuaternionTensor(BaseCausaloid<Complex<f64>, CausalTensor<Quaternion<f64>>>),
    ComplexToUncertainBool(BaseCausaloid<Complex<f64>, UncertainBool>),
    ComplexToUncertainFloat(BaseCausaloid<Complex<f64>, UncertainF64>),
    ComplexToContextualLink(BaseCausaloid<Complex<f64>, ContextoidId>),
    ComplexToRelayTo(BaseCausaloid<Complex<f64>, IdentificationValue>),
    ComplexTensorToDeterministic(BaseCausaloid<CausalTensor<Complex<f64>>, bool>),
    ComplexTensorToNumber(BaseCausaloid<CausalTensor<Complex<f64>>, NumericValue>),
    ComplexTensorToNumerical(BaseCausaloid<CausalTensor<Complex<f64>>, f64>),
    ComplexTensorToProbabilistic(BaseCausaloid<CausalTensor<Complex<f64>>, f64>),
    ComplexTensorToTensor(BaseCausaloid<CausalTensor<Complex<f64>>, CausalTensor<f64>>),
    ComplexTensorToComplex(BaseCausaloid<CausalTensor<Complex<f64>>, Complex<f64>>),
    ComplexTensorToComplexTensor(
        BaseCausaloid<CausalTensor<Complex<f64>>, CausalTensor<Complex<f64>>>,
    ),
    ComplexTensorToQuaternion(BaseCausaloid<CausalTensor<Complex<f64>>, Quaternion<f64>>),
    ComplexTensorToQuaternionTensor(
        BaseCausaloid<CausalTensor<Complex<f64>>, CausalTensor<Quaternion<f64>>>,
    ),
    ComplexTensorToUncertainBool(BaseCausaloid<CausalTensor<Complex<f64>>, UncertainBool>),
    ComplexTensorToUncertainFloat(BaseCausaloid<CausalTensor<Complex<f64>>, UncertainF64>),
    ComplexTensorToContextualLink(BaseCausaloid<CausalTensor<Complex<f64>>, ContextoidId>),
    ComplexTensorToRelayTo(BaseCausaloid<CausalTensor<Complex<f64>>, IdentificationValue>),
    QuaternionToDeterministic(BaseCausaloid<Quaternion<f64>, bool>),
    QuaternionToNumber(BaseCausaloid<Quaternion<f64>, NumericValue>),
    QuaternionToNumerical(BaseCausaloid<Quaternion<f64>, f64>),
    QuaternionToProbabilistic(BaseCausaloid<Quaternion<f64>, f64>),
    QuaternionToTensor(BaseCausaloid<Quaternion<f64>, CausalTensor<f64>>),
    QuaternionToComplex(BaseCausaloid<Quaternion<f64>, Complex<f64>>),
    QuaternionToComplexTensor(BaseCausaloid<Quaternion<f64>, CausalTensor<Complex<f64>>>),
    QuaternionToQuaternion(BaseCausaloid<Quaternion<f64>, Quaternion<f64>>),
    QuaternionToQuaternionTensor(BaseCausaloid<Quaternion<f64>, CausalTensor<Quaternion<f64>>>),
    QuaternionToUncertainBool(BaseCausaloid<Quaternion<f64>, UncertainBool>),
    QuaternionToUncertainFloat(BaseCausaloid<Quaternion<f64>, UncertainF64>),
    QuaternionToContextualLink(BaseCausaloid<Quaternion<f64>, ContextoidId>),
    QuaternionToRelayTo(BaseCausaloid<Quaternion<f64>, IdentificationValue>),
    QuaternionTensorToDeterministic(BaseCausaloid<CausalTensor<Quaternion<f64>>, bool>),
    QuaternionTensorToNumber(BaseCausaloid<CausalTensor<Quaternion<f64>>, NumericValue>),
    QuaternionTensorToNumerical(BaseCausaloid<CausalTensor<Quaternion<f64>>, f64>),
    QuaternionTensorToProbabilistic(BaseCausaloid<CausalTensor<Quaternion<f64>>, f64>),
    QuaternionTensorToTensor(BaseCausaloid<CausalTensor<Quaternion<f64>>, CausalTensor<f64>>),
    QuaternionTensorToComplex(BaseCausaloid<CausalTensor<Quaternion<f64>>, Complex<f64>>),
    QuaternionTensorToComplexTensor(
        BaseCausaloid<CausalTensor<Quaternion<f64>>, CausalTensor<Complex<f64>>>,
    ),
    QuaternionTensorToQuaternion(BaseCausaloid<CausalTensor<Quaternion<f64>>, Quaternion<f64>>),
    QuaternionTensorToQuaternionTensor(
        BaseCausaloid<CausalTensor<Quaternion<f64>>, CausalTensor<Quaternion<f64>>>,
    ),
    QuaternionTensorToUncertainBool(BaseCausaloid<CausalTensor<Quaternion<f64>>, UncertainBool>),
    QuaternionTensorToUncertainFloat(BaseCausaloid<CausalTensor<Quaternion<f64>>, UncertainF64>),
    QuaternionTensorToContextualLink(BaseCausaloid<CausalTensor<Quaternion<f64>>, ContextoidId>),
    QuaternionTensorToRelayTo(BaseCausaloid<CausalTensor<Quaternion<f64>>, IdentificationValue>),
    UncertainBoolToDeterministic(BaseCausaloid<UncertainBool, bool>),
    UncertainBoolToNumber(BaseCausaloid<UncertainBool, NumericValue>),
    UncertainBoolToNumerical(BaseCausaloid<UncertainBool, f64>),
    UncertainBoolToProbabilistic(BaseCausaloid<UncertainBool, f64>),
    UncertainBoolToTensor(BaseCausaloid<UncertainBool, CausalTensor<f64>>),
    UncertainBoolToComplex(BaseCausaloid<UncertainBool, Complex<f64>>),
    UncertainBoolToComplexTensor(BaseCausaloid<UncertainBool, CausalTensor<Complex<f64>>>),
    UncertainBoolToQuaternion(BaseCausaloid<UncertainBool, Quaternion<f64>>),
    UncertainBoolToQuaternionTensor(BaseCausaloid<UncertainBool, CausalTensor<Quaternion<f64>>>),
    UncertainBoolToUncertainBool(BaseCausaloid<UncertainBool, UncertainBool>),
    UncertainBoolToUncertainFloat(BaseCausaloid<UncertainBool, UncertainF64>),
    UncertainBoolToContextualLink(BaseCausaloid<UncertainBool, ContextoidId>),
    UncertainBoolToRelayTo(BaseCausaloid<UncertainBool, IdentificationValue>),
    UncertainFloatToDeterministic(BaseCausaloid<UncertainF64, bool>),
    UncertainFloatToNumber(BaseCausaloid<UncertainF64, NumericValue>),
    UncertainFloatToNumerical(BaseCausaloid<UncertainF64, f64>),
    UncertainFloatToProbabilistic(BaseCausaloid<UncertainF64, f64>),
    UncertainFloatToTensor(BaseCausaloid<UncertainF64, CausalTensor<f64>>),
    UncertainFloatToComplex(BaseCausaloid<UncertainF64, Complex<f64>>),
    UncertainFloatToComplexTensor(BaseCausaloid<UncertainF64, CausalTensor<Complex<f64>>>),
    UncertainFloatToQuaternion(BaseCausaloid<UncertainF64, Quaternion<f64>>),
    UncertainFloatToQuaternionTensor(BaseCausaloid<UncertainF64, CausalTensor<Quaternion<f64>>>),
    UncertainFloatToUncertainBool(BaseCausaloid<UncertainF64, UncertainBool>),
    UncertainFloatToUncertainFloat(BaseCausaloid<UncertainF64, UncertainF64>),
    UncertainFloatToContextualLink(BaseCausaloid<UncertainF64, ContextoidId>),
    UncertainFloatToRelayTo(BaseCausaloid<UncertainF64, IdentificationValue>),
    ContextualLinkToDeterministic(BaseCausaloid<ContextoidId, bool>),
    ContextualLinkToNumber(BaseCausaloid<ContextoidId, NumericValue>),
    ContextualLinkToNumerical(BaseCausaloid<ContextoidId, f64>),
    ContextualLinkToProbabilistic(BaseCausaloid<ContextoidId, f64>),
    ContextualLinkToTensor(BaseCausaloid<ContextoidId, CausalTensor<f64>>),
    ContextualLinkToComplex(BaseCausaloid<ContextoidId, Complex<f64>>),
    ContextualLinkToComplexTensor(BaseCausaloid<ContextoidId, CausalTensor<Complex<f64>>>),
    ContextualLinkToQuaternion(BaseCausaloid<ContextoidId, Quaternion<f64>>),
    ContextualLinkToQuaternionTensor(BaseCausaloid<ContextoidId, CausalTensor<Quaternion<f64>>>),
    ContextualLinkToUncertainBool(BaseCausaloid<ContextoidId, UncertainBool>),
    ContextualLinkToUncertainFloat(BaseCausaloid<ContextoidId, UncertainF64>),
    ContextualLinkToContextualLink(BaseCausaloid<ContextoidId, ContextoidId>),
    ContextualLinkToRelayTo(BaseCausaloid<ContextoidId, IdentificationValue>),
    RelayToToDeterministic(BaseCausaloid<IdentificationValue, bool>),
    RelayToToNumber(BaseCausaloid<IdentificationValue, NumericValue>),
    RelayToToNumerical(BaseCausaloid<IdentificationValue, f64>),
    RelayToToProbabilistic(BaseCausaloid<IdentificationValue, f64>),
    RelayToToTensor(BaseCausaloid<IdentificationValue, CausalTensor<f64>>),
    RelayToToComplex(BaseCausaloid<IdentificationValue, Complex<f64>>),
    RelayToToComplexTensor(BaseCausaloid<IdentificationValue, CausalTensor<Complex<f64>>>),
    RelayToToQuaternion(BaseCausaloid<IdentificationValue, Quaternion<f64>>),
    RelayToToQuaternionTensor(BaseCausaloid<IdentificationValue, CausalTensor<Quaternion<f64>>>),
    RelayToToUncertainBool(BaseCausaloid<IdentificationValue, UncertainBool>),
    RelayToToUncertainFloat(BaseCausaloid<IdentificationValue, UncertainF64>),
    RelayToToContextualLink(BaseCausaloid<IdentificationValue, ContextoidId>),
    RelayToToRelayTo(BaseCausaloid<IdentificationValue, IdentificationValue>),
    // === END OF STATICALLY-KNOWN TYPES ===

    // === OPT-IN FOR EXTENSIBILITY (DYNAMIC PATH) ===
    // #[cfg(feature = "dynamic_external_types")]
    // External(Box<dyn MonadicCausable<CausalMonad> + Send + Sync>),
}

// Implement the unified evaluation logic
impl RegisteredCausaloid {
    pub fn evaluate(&self, effect: &PropagatingEffect) -> PropagatingEffect {
        match self {
            // This `match` is the static dispatch. The compiler knows every possible
            // path and can optimize it heavily.
            RegisteredCausaloid::DeterministicToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::DeterministicToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::NumberToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::NumericalToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::ProbabilisticToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::TensorToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::ComplexTensorToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::QuaternionTensorToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainBoolToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::UncertainFloatToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::ContextualLinkToRelayTo(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToDeterministic(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToNumber(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToNumerical(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToProbabilistic(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToComplex(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToComplexTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToQuaternion(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToQuaternionTensor(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToUncertainBool(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToUncertainFloat(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToContextualLink(c) => c.evaluate(effect),
            RegisteredCausaloid::RelayToToRelayTo(c) => c.evaluate(effect),
        }
    }
}
