/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2023 - 2026. The DeepCausality Authors and Contributors. All Rights Reserved.
 */

//! The eighteen dimensionless-number kernels, against independent oracles.
//!
//! # What changed, and why
//!
//! The previous suite computed its own expectations by retyping each kernel's formula —
//! `let expected = 1000.0 * 9.8 * 1.0e-4 / 0.072;` beside a call to `bond_number_kernel` — which
//! asserts only that an expression was written the same way twice and passes against a kernel that
//! is wrong in the same way. It also tested one hand-chosen input per kernel.
//!
//! Both are replaced. The expected values in the tables below are generated by
//! `scripts/physics_oracles.py`, which evaluates the **textbook definitions** in 50-digit decimal —
//! a different language, a different source for the formula, and more precision than `f64` carries,
//! so the assertions measure the kernel's error against the mathematics rather than against a
//! second copy of itself. Definitions are cited in that script's header (White, *Fluid Mechanics*
//! 7th ed. Table 5.2; Bird, Stewart & Lightfoot, *Transport Phenomena* 2nd ed.; Chapman & Cowling).
//!
//! # Ranges, not points
//!
//! Each table spans many decades and several physical regimes — creeping flow to re-entry, microns
//! to kilometres, liquid metals at `Pr ≈ 0.003` to heavy oils at `Pr ≈ 1e4`, terrestrial, lunar and
//! Jovian gravity. A kernel that is right at one comfortable value and wrong at the extremes fails
//! here.
//!
//! # The identities are the strongest check
//!
//! `Pe = Re·Pr`, `Ra = Gr·Pr` and `Le = Sc/Pr` each relate three kernels that share no code. They
//! cannot be satisfied by a formula retyped consistently, and they catch an error in any one of the
//! three from the other two. The module under test names all three in its own documentation.

use deep_causality_physics::{
    Density, KinematicViscosity, Length, PhysicsErrorEnum, Speed, Viscosity, bond_number_kernel,
    capillary_number_kernel, eckert_number_kernel, froude_number_kernel, grashof_number_kernel,
    knudsen_number_kernel, lewis_number_kernel, mach_number_kernel, nusselt_number_kernel,
    particle_stokes_number_kernel, peclet_number_kernel, prandtl_number_kernel,
    rayleigh_number_kernel, reynolds_number_kernel, richardson_number_kernel,
    schmidt_number_kernel, strouhal_number_kernel, weber_number_kernel,
};

/// Relative tolerance. The oracle is exact to 50 digits, so what is being measured is the kernel's
/// own `f64` rounding: a handful of operations, each half an ulp.
const REL: f64 = 1e-14;

/// Asserts `got` matches the oracle to `REL` *relatively*, which is the only scale-free way to
/// compare across tables spanning `1e-6` to `1e15`.
#[track_caller]
fn close(got: f64, want: f64, case: &str) {
    let scale = want.abs().max(1.0);
    assert!(
        (got - want).abs() <= REL * scale,
        "{case}: got {got:.17e}, oracle {want:.17e}, relative error {:.3e}",
        ((got - want) / scale).abs()
    );
}

fn speed(v: f64) -> Speed<f64> {
    Speed::new(v).unwrap()
}
fn length(v: f64) -> Length<f64> {
    Length::new(v).unwrap()
}
fn nu(v: f64) -> KinematicViscosity<f64> {
    KinematicViscosity::new(v).unwrap()
}
fn density(v: f64) -> Density<f64> {
    Density::new(v).unwrap()
}
fn viscosity(v: f64) -> Viscosity<f64> {
    Viscosity::new(v).unwrap()
}

// =============================================================================
// Oracle tables
// =============================================================================

/// `(u, L, nu, expected)`
pub const REYNOLDS: &[[f64; 4]] = &[
    [1e-06, 1e-06, 1e-06, 1e-06],
    [0.001, 0.001, 1.5e-05, 0.06666666666666667],
    [1.0, 0.01, 1e-06, 10000.0],
    [10.0, 2.5, 1.5e-05, 1666666.6666666667],
    [250.0, 60.0, 1.46e-05, 1027397260.2739726],
    [7800.0, 10.0, 0.0001, 780000000.0],
    [100000.0, 1000.0, 1e-07, 1000000000000000.0],
    [0.037, 0.0089, 2.3e-06, 143.17391304347825],
];

/// `(u, a, expected)`
pub const MACH: &[[f64; 3]] = &[
    [0.001, 340.29, 2.9386699579770196e-06],
    [34.029, 340.29, 0.1],
    [340.29, 340.29, 1.0],
    [680.58, 340.29, 2.0],
    [1701.45, 340.29, 5.0],
    [7800.0, 295.0, 26.440677966101696],
    [10000.0, 0.01, 1000000.0],
];

/// `(u, g, L, expected)`
pub const FROUDE: &[[f64; 4]] = &[
    [0.001, 9.80665, 0.001, 0.01009809988551276],
    [0.5, 9.80665, 0.1, 0.5049049942756381],
    [10.0, 9.80665, 2.5, 2.0196199771025523],
    [3.0, 1.62, 100.0, 0.23570226039551584],
    [15.0, 24.79, 1.0, 3.012679939775216],
    [1000.0, 9.80665, 1000000.0, 0.3193299567810587],
    [2.7, 3.72, 0.35, 2.366237169223285],
];

/// `(rho, u, L, sigma, expected)`
pub const WEBER: &[[f64; 5]] = &[
    [1000.0, 2.0, 0.001, 0.072, 55.55555555555556],
    [1.225, 100.0, 0.05, 0.072, 8506.944444444445],
    [13546.0, 0.5, 0.002, 0.4865, 13.921891058581705],
    [789.0, 10.0, 0.0001, 0.0223, 353.8116591928251],
    [1000.0, 0.001, 1e-06, 0.072, 1.3888888888888889e-08],
    [1.0, 10000.0, 1000.0, 0.001, 100000000000000.0],
];

/// `(nu, alpha, expected)`
pub const PRANDTL: &[[f64; 3]] = &[
    [1.5e-05, 2.2e-05, 0.6818181818181818],
    [1e-06, 1.43e-07, 6.993006993006993],
    [1.1e-07, 4.3e-05, 0.0025581395348837207],
    [0.0009, 8.6e-08, 10465.116279069767],
    [1e-09, 1e-09, 1.0],
    [1000.0, 0.001, 1000000.0],
];

/// `(u, L, alpha, expected)`
pub const PECLET: &[[f64; 4]] = &[
    [1e-06, 1e-06, 1e-07, 1e-05],
    [1.0, 0.01, 1.43e-07, 69930.06993006993],
    [10.0, 2.5, 2.2e-05, 1136363.6363636365],
    [250.0, 60.0, 2.2e-05, 681818181.8181819],
    [10000.0, 1000.0, 1e-08, 1000000000000000.0],
];

/// `(f, L, u, expected)`
pub const STROUHAL: &[[f64; 4]] = &[
    [0.2, 1.0, 1.0, 0.2],
    [120.0, 0.01, 10.0, 0.12],
    [0.001, 1000.0, 1.0, 1.0],
    [5.0, 0.05, 1.2, 0.20833333333333334],
    [1000000.0, 1e-06, 0.001, 1000.0],
];

/// `(lam, L, expected)`
pub const KNUDSEN: &[[f64; 3]] = &[
    [6.8e-08, 1.0, 6.8e-08],
    [6.8e-08, 1e-06, 0.068],
    [0.001, 0.001, 1.0],
    [1.0, 1e-09, 1000000000.0],
    [1e-12, 1000.0, 1e-15],
];

/// `(g, beta, dT, L, u, expected)`
pub const RICHARDSON: &[[f64; 6]] = &[
    [9.80665, 0.0034, 10.0, 1.0, 1.0, 0.3334261],
    [9.80665, 0.000207, 50.0, 0.1, 0.01, 101.4988275],
    [1.62, 0.001, 100.0, 10.0, 5.0, 0.0648],
    [9.80665, 1e-06, 0.001, 0.001, 1000.0, 9.80665e-18],
];

/// `(g, beta, dT, L, nu, alpha, expected)`
pub const RAYLEIGH: &[[f64; 7]] = &[
    [
        9.80665,
        0.0034,
        10.0,
        0.1,
        1.5e-05,
        2.2e-05,
        1010382.1212121212,
    ],
    [
        9.80665,
        0.000207,
        20.0,
        0.05,
        1e-06,
        1.43e-07,
        35489100.52447552,
    ],
    [1.62, 0.001, 5.0, 2.0, 0.0001, 1e-05, 64800000.0],
    [9.80665, 1e-05, 0.01, 0.001, 0.001, 0.001, 9.80665e-10],
];

/// `(g, beta, dT, L, nu, expected)`
pub const GRASHOF: &[[f64; 6]] = &[
    [9.80665, 0.0034, 10.0, 0.1, 1.5e-05, 1481893.7777777778],
    [9.80665, 0.000207, 20.0, 0.05, 1e-06, 5074941.375],
    [1.62, 0.001, 5.0, 2.0, 0.0001, 6480000.0],
    [24.79, 0.0001, 1000.0, 100.0, 0.01, 24790000000.0],
];

/// `(u, cp, dT, expected)`
pub const ECKERT: &[[f64; 4]] = &[
    [2000.0, 1004.0, 3000.0, 1.3280212483399734],
    [10.0, 4184.0, 1.0, 0.02390057361376673],
    [0.001, 1000.0, 1000.0, 1e-12],
    [7800.0, 1004.0, 20000.0, 3.0298804780876494],
    [10000.0, 0.001, 0.001, 100000000000000.0],
];

/// `(nu, Dm, expected)`
pub const SCHMIDT: &[[f64; 3]] = &[
    [1.5e-05, 2e-05, 0.75],
    [1e-06, 1.5e-09, 666.6666666666666],
    [1e-09, 0.001, 1e-06],
    [0.0009, 1e-10, 9000000.0],
];

/// `(alpha, Dm, expected)`
pub const LEWIS: &[[f64; 3]] = &[
    [2.2e-05, 2e-05, 1.1],
    [1.43e-07, 1.5e-09, 95.33333333333333],
    [0.001, 1e-09, 1000000.0],
    [1e-09, 0.001, 1e-06],
];

/// `(tau, u, L, expected)`
pub const STOKES: &[[f64; 4]] = &[
    [0.001, 10.0, 0.1, 0.1],
    [1e-06, 1.0, 0.001, 0.001],
    [1.0, 1000.0, 0.01, 100000.0],
    [1e-09, 0.001, 1000.0, 1e-15],
];

/// `(mu, u, sigma, expected)`
pub const CAPILLARY: &[[f64; 4]] = &[
    [0.001, 0.01, 0.072, 0.0001388888888888889],
    [1.5e-05, 100.0, 0.072, 0.020833333333333332],
    [1.0, 1e-06, 0.0223, 4.484304932735426e-05],
    [0.1, 1.0, 0.4865, 0.20554984583761562],
    [1e-06, 1000000.0, 0.001, 1000.0],
];

/// `(rho, g, L, sigma, expected)`
pub const BOND: &[[f64; 5]] = &[
    [1000.0, 9.80665, 0.01, 0.072, 13.620347222222222],
    [1000.0, 9.80665, 0.001, 0.072, 0.13620347222222223],
    [13546.0, 9.80665, 0.005, 0.4865, 6.826355647482014],
    [789.0, 1.62, 0.02, 0.0223, 22.92699551569507],
    [1.0, 24.79, 1000.0, 0.001, 24790000000.0],
];

/// `(h, L, k, expected)`
pub const NUSSELT: &[[f64; 4]] = &[
    [10.0, 1.0, 0.0257, 389.10505836575874],
    [1000.0, 0.05, 0.6, 83.33333333333333],
    [0.001, 0.001, 1000.0, 1e-09],
    [100000.0, 10.0, 401.0, 2493.7655860349128],
    [25.0, 0.3, 0.14, 53.57142857142857],
];

// =============================================================================
// Value tests: every kernel, over its whole table
// =============================================================================

#[test]
fn test_reynolds_over_eight_decades_of_input() {
    for [u, l, v, want] in REYNOLDS {
        let got = reynolds_number_kernel(&speed(*u), &length(*l), &nu(*v)).unwrap();
        close(got, *want, &format!("Re(u={u:e}, L={l:e}, nu={v:e})"));
    }
}

#[test]
fn test_mach_from_creeping_to_hypersonic() {
    for [u, a, want] in MACH {
        let got = mach_number_kernel(&speed(*u), &speed(*a)).unwrap();
        close(got, *want, &format!("Ma(u={u:e}, a={a:e})"));
    }
}

#[test]
fn test_froude_across_three_gravities() {
    for [u, g, l, want] in FROUDE {
        let got = froude_number_kernel(&speed(*u), *g, &length(*l)).unwrap();
        close(got, *want, &format!("Fr(u={u:e}, g={g}, L={l:e})"));
    }
}

#[test]
fn test_weber_across_four_fluids() {
    for [rho, u, l, sigma, want] in WEBER {
        let got = weber_number_kernel(&density(*rho), &speed(*u), &length(*l), *sigma).unwrap();
        close(
            got,
            *want,
            &format!("We(rho={rho}, u={u}, L={l:e}, sigma={sigma})"),
        );
    }
}

#[test]
fn test_prandtl_from_liquid_metal_to_engine_oil() {
    for [v, alpha, want] in PRANDTL {
        let got = prandtl_number_kernel(&nu(*v), *alpha).unwrap();
        close(got, *want, &format!("Pr(nu={v:e}, alpha={alpha:e})"));
    }
}

#[test]
fn test_peclet_over_its_range() {
    for [u, l, alpha, want] in PECLET {
        let got = peclet_number_kernel(&speed(*u), &length(*l), *alpha).unwrap();
        close(
            got,
            *want,
            &format!("Pe(u={u:e}, L={l:e}, alpha={alpha:e})"),
        );
    }
}

#[test]
fn test_strouhal_over_its_range() {
    for [f, l, u, want] in STROUHAL {
        let got = strouhal_number_kernel(*f, &length(*l), &speed(*u)).unwrap();
        close(got, *want, &format!("St(f={f:e}, L={l:e}, u={u:e})"));
    }
}

#[test]
fn test_knudsen_from_continuum_to_free_molecular() {
    for [lam, l, want] in KNUDSEN {
        let got = knudsen_number_kernel(*lam, &length(*l)).unwrap();
        close(got, *want, &format!("Kn(lambda={lam:e}, L={l:e})"));
    }
}

#[test]
fn test_richardson_over_its_range() {
    for [g, beta, dt, l, u, want] in RICHARDSON {
        let got = richardson_number_kernel(*g, *beta, *dt, &length(*l), &speed(*u)).unwrap();
        close(
            got,
            *want,
            &format!("Ri(g={g}, beta={beta:e}, dT={dt}, L={l:e}, u={u:e})"),
        );
    }
}

#[test]
fn test_rayleigh_over_its_range() {
    for [g, beta, dt, l, v, alpha, want] in RAYLEIGH {
        let got = rayleigh_number_kernel(*g, *beta, *dt, &length(*l), &nu(*v), *alpha).unwrap();
        close(
            got,
            *want,
            &format!("Ra(g={g}, beta={beta:e}, dT={dt}, L={l:e})"),
        );
    }
}

#[test]
fn test_grashof_over_its_range() {
    for [g, beta, dt, l, v, want] in GRASHOF {
        let got = grashof_number_kernel(*g, *beta, *dt, &length(*l), &nu(*v)).unwrap();
        close(
            got,
            *want,
            &format!("Gr(g={g}, beta={beta:e}, dT={dt}, L={l:e})"),
        );
    }
}

#[test]
fn test_eckert_over_its_range() {
    for [u, cp, dt, want] in ECKERT {
        let got = eckert_number_kernel(&speed(*u), *cp, *dt).unwrap();
        close(got, *want, &format!("Ec(u={u:e}, cp={cp:e}, dT={dt:e})"));
    }
}

#[test]
fn test_schmidt_over_its_range() {
    for [v, dm, want] in SCHMIDT {
        let got = schmidt_number_kernel(&nu(*v), *dm).unwrap();
        close(got, *want, &format!("Sc(nu={v:e}, D={dm:e})"));
    }
}

#[test]
fn test_lewis_over_its_range() {
    for [alpha, dm, want] in LEWIS {
        let got = lewis_number_kernel(*alpha, *dm).unwrap();
        close(got, *want, &format!("Le(alpha={alpha:e}, D={dm:e})"));
    }
}

#[test]
fn test_particle_stokes_over_its_range() {
    for [tau, u, l, want] in STOKES {
        let got = particle_stokes_number_kernel(*tau, &speed(*u), &length(*l)).unwrap();
        close(got, *want, &format!("St_p(tau={tau:e}, u={u:e}, L={l:e})"));
    }
}

#[test]
fn test_capillary_over_its_range() {
    for [mu, u, sigma, want] in CAPILLARY {
        let got = capillary_number_kernel(&viscosity(*mu), &speed(*u), *sigma).unwrap();
        close(
            got,
            *want,
            &format!("Ca(mu={mu:e}, u={u:e}, sigma={sigma:e})"),
        );
    }
}

#[test]
fn test_bond_over_its_range() {
    for [rho, g, l, sigma, want] in BOND {
        let got = bond_number_kernel(&density(*rho), *g, &length(*l), *sigma).unwrap();
        close(
            got,
            *want,
            &format!("Bo(rho={rho}, g={g}, L={l:e}, sigma={sigma})"),
        );
    }
}

#[test]
fn test_nusselt_over_its_range() {
    for [h, l, k, want] in NUSSELT {
        let got = nusselt_number_kernel(*h, &length(*l), *k).unwrap();
        close(got, *want, &format!("Nu(h={h:e}, L={l:e}, k={k:e})"));
    }
}

// =============================================================================
// Cross-kernel identities
//
// These share no code with any single kernel, so they cannot be satisfied by a formula that was
// retyped consistently. The module under test names all three in its own header.
// =============================================================================

#[test]
fn test_peclet_equals_reynolds_times_prandtl() {
    // Pe = uL/α, Re = uL/ν, Pr = ν/α ⇒ Pe = Re·Pr, for any ν.
    for &(u, l, v, alpha) in &[
        (1.0f64, 0.01f64, 1.0e-6f64, 1.43e-7f64),
        (250.0, 60.0, 1.46e-5, 2.2e-5),
        (1e-3, 1e-3, 1.5e-5, 2.2e-5),
        (7800.0, 10.0, 1e-4, 1e-5),
        (1e5, 1e3, 1e-7, 1e-9),
    ] {
        let pe = peclet_number_kernel(&speed(u), &length(l), alpha).unwrap();
        let re = reynolds_number_kernel(&speed(u), &length(l), &nu(v)).unwrap();
        let pr = prandtl_number_kernel(&nu(v), alpha).unwrap();
        close(pe, re * pr, &format!("Pe = Re*Pr at u={u:e}, L={l:e}"));
    }
}

#[test]
fn test_rayleigh_equals_grashof_times_prandtl() {
    // Ra = gβΔT·L³/(να), Gr = gβΔT·L³/ν², Pr = ν/α ⇒ Ra = Gr·Pr.
    for &(g, beta, dt, l, v, alpha) in &[
        (9.80665f64, 3.4e-3f64, 10.0f64, 0.1f64, 1.5e-5f64, 2.2e-5f64),
        (9.80665, 2.07e-4, 20.0, 0.05, 1.0e-6, 1.43e-7),
        (1.62, 1e-3, 5.0, 2.0, 1e-4, 1e-5),
        (24.79, 1e-5, 1e3, 1e2, 1e-3, 1e-6),
    ] {
        let ra = rayleigh_number_kernel(g, beta, dt, &length(l), &nu(v), alpha).unwrap();
        let gr = grashof_number_kernel(g, beta, dt, &length(l), &nu(v)).unwrap();
        let pr = prandtl_number_kernel(&nu(v), alpha).unwrap();
        close(ra, gr * pr, &format!("Ra = Gr*Pr at L={l:e}, nu={v:e}"));
    }
}

#[test]
fn test_lewis_equals_schmidt_over_prandtl() {
    // Le = α/D, Sc = ν/D, Pr = ν/α ⇒ Le = Sc/Pr.
    for &(v, alpha, dm) in &[
        (1.5e-5f64, 2.2e-5f64, 2.0e-5f64),
        (1.0e-6, 1.43e-7, 1.5e-9),
        (9.0e-4, 8.6e-8, 1e-10),
        (1e-3, 1e-3, 1e-3),
    ] {
        let le = lewis_number_kernel(alpha, dm).unwrap();
        let sc = schmidt_number_kernel(&nu(v), dm).unwrap();
        let pr = prandtl_number_kernel(&nu(v), alpha).unwrap();
        close(
            le,
            sc / pr,
            &format!("Le = Sc/Pr at nu={v:e}, alpha={alpha:e}"),
        );
    }
}

#[test]
fn test_mach_and_froude_are_one_at_their_own_reference_speed() {
    // Definitional fixed points: Ma = 1 exactly when u = a, and Fr = 1 exactly when u = sqrt(gL).
    // No oracle needed — the value is forced by the definition.
    for a in [1e-3f64, 1.0, 340.29, 1e6] {
        assert_eq!(mach_number_kernel(&speed(a), &speed(a)).unwrap(), 1.0);
    }
    for (g, l) in [(9.80665f64, 2.5f64), (1.62, 100.0), (24.79, 1e-3)] {
        let got = froude_number_kernel(&speed((g * l).sqrt()), g, &length(l)).unwrap();
        close(got, 1.0, &format!("Fr = 1 at u = sqrt(g*L), g={g}, L={l}"));
    }
}

#[test]
fn test_the_ratio_kernels_are_reciprocal_under_swapped_arguments() {
    // Pr, Sc and Le are each a ratio of two diffusivities, so swapping them inverts the result.
    // An invariant, independent of what either value is.
    for (a, b) in [(1.5e-5f64, 2.2e-5f64), (9.0e-4, 8.6e-8), (1e-9, 1e3)] {
        let fwd = prandtl_number_kernel(&nu(a), b).unwrap();
        let rev = prandtl_number_kernel(&nu(b), a).unwrap();
        close(
            fwd * rev,
            1.0,
            &format!("Pr(a,b)*Pr(b,a) = 1 at {a:e}, {b:e}"),
        );
        let lf = lewis_number_kernel(a, b).unwrap();
        let lr = lewis_number_kernel(b, a).unwrap();
        close(
            lf * lr,
            1.0,
            &format!("Le(a,b)*Le(b,a) = 1 at {a:e}, {b:e}"),
        );
    }
}

// =============================================================================
// Scaling laws: how each kernel must respond to its inputs
// =============================================================================

#[test]
fn test_weber_is_quadratic_in_speed_and_linear_in_length() {
    // We ∝ ρu²L/σ. Doubling u must quadruple it; doubling L must double it. Catches a squared
    // term written linear, which a single-point value test cannot see.
    let (rho, l, sigma) = (1000.0f64, 0.001f64, 0.072f64);
    for u in [1e-3f64, 0.5, 2.0, 100.0] {
        let base = weber_number_kernel(&density(rho), &speed(u), &length(l), sigma).unwrap();
        let doubled_u =
            weber_number_kernel(&density(rho), &speed(2.0 * u), &length(l), sigma).unwrap();
        let doubled_l =
            weber_number_kernel(&density(rho), &speed(u), &length(2.0 * l), sigma).unwrap();
        close(
            doubled_u,
            4.0 * base,
            &format!("We(2u) = 4We(u) at u={u:e}"),
        );
        close(
            doubled_l,
            2.0 * base,
            &format!("We(2L) = 2We(L) at u={u:e}"),
        );
    }
}

#[test]
fn test_grashof_is_cubic_in_length_and_rayleigh_likewise() {
    // Both carry L³. Doubling L multiplies them by eight.
    let (g, beta, dt, v, alpha) = (9.80665f64, 3.4e-3f64, 10.0f64, 1.5e-5f64, 2.2e-5f64);
    for l in [1e-3f64, 0.05, 1.0, 100.0] {
        let gr = grashof_number_kernel(g, beta, dt, &length(l), &nu(v)).unwrap();
        let gr2 = grashof_number_kernel(g, beta, dt, &length(2.0 * l), &nu(v)).unwrap();
        close(gr2, 8.0 * gr, &format!("Gr(2L) = 8Gr(L) at L={l:e}"));
        let ra = rayleigh_number_kernel(g, beta, dt, &length(l), &nu(v), alpha).unwrap();
        let ra2 = rayleigh_number_kernel(g, beta, dt, &length(2.0 * l), &nu(v), alpha).unwrap();
        close(ra2, 8.0 * ra, &format!("Ra(2L) = 8Ra(L) at L={l:e}"));
    }
}

#[test]
fn test_froude_is_inverse_square_root_in_gravity_and_length() {
    // Fr ∝ u/sqrt(gL): quadrupling g must halve it.
    for (u, g, l) in [
        (10.0f64, 9.80665f64, 2.5f64),
        (0.5, 1.62, 0.1),
        (1e3, 24.79, 1e6),
    ] {
        let base = froude_number_kernel(&speed(u), g, &length(l)).unwrap();
        let quad_g = froude_number_kernel(&speed(u), 4.0 * g, &length(l)).unwrap();
        let quad_l = froude_number_kernel(&speed(u), g, &length(4.0 * l)).unwrap();
        close(quad_g, 0.5 * base, &format!("Fr(4g) = Fr/2 at g={g}"));
        close(quad_l, 0.5 * base, &format!("Fr(4L) = Fr/2 at L={l:e}"));
    }
}

#[test]
fn test_richardson_is_inverse_square_in_speed() {
    // Ri ∝ 1/u². Doubling u must quarter it.
    for u in [1e-2f64, 1.0, 50.0] {
        let base =
            richardson_number_kernel(9.80665, 3.4e-3, 10.0, &length(1.0), &speed(u)).unwrap();
        let doubled =
            richardson_number_kernel(9.80665, 3.4e-3, 10.0, &length(1.0), &speed(2.0 * u)).unwrap();
        close(doubled, 0.25 * base, &format!("Ri(2u) = Ri/4 at u={u:e}"));
    }
}

// =============================================================================
// Corner cases: a zero numerator is a value, not a failure
// =============================================================================

#[test]
fn test_a_zero_numerator_gives_zero_rather_than_an_error() {
    // Every one of these is a well-posed zero: a fluid at rest has Re = Ma = We = 0. Only the
    // divisor may be refused, so these must succeed and return exactly zero.
    assert_eq!(
        reynolds_number_kernel(&speed(0.0), &length(1.0), &nu(1e-6)).unwrap(),
        0.0
    );
    assert_eq!(
        mach_number_kernel(&speed(0.0), &speed(340.29)).unwrap(),
        0.0
    );
    assert_eq!(
        weber_number_kernel(&density(1000.0), &speed(0.0), &length(1.0), 0.072).unwrap(),
        0.0
    );
    assert_eq!(
        froude_number_kernel(&speed(0.0), 9.80665, &length(1.0)).unwrap(),
        0.0
    );
    assert_eq!(knudsen_number_kernel(0.0, &length(1.0)).unwrap(), 0.0);
    assert_eq!(nusselt_number_kernel(0.0, &length(1.0), 0.6).unwrap(), 0.0);
    assert_eq!(
        eckert_number_kernel(&speed(0.0), 1004.0, 100.0).unwrap(),
        0.0
    );
}

#[test]
fn test_a_zero_length_is_a_value_where_it_is_a_numerator() {
    // L in the numerator: Re and Nu are zero at zero length. This is the mirror of the divisor
    // case below, and the two must not be conflated.
    assert_eq!(
        reynolds_number_kernel(&speed(1.0), &length(0.0), &nu(1e-6)).unwrap(),
        0.0
    );
    assert_eq!(nusselt_number_kernel(10.0, &length(0.0), 0.6).unwrap(), 0.0);
}

// =============================================================================
// Error paths: every divisor guard, and the invariant guard on Froude
// =============================================================================

#[track_caller]
fn assert_invariant_broken(err: deep_causality_physics::PhysicsError, what: &str) {
    match err.0 {
        PhysicsErrorEnum::PhysicalInvariantBroken(_) => {}
        other => panic!("{what}: expected PhysicalInvariantBroken, got {other:?}"),
    }
}

#[test]
fn test_every_kernel_refuses_a_zero_divisor() {
    // One case per kernel that has a divisor, so no guard is left unexercised.
    assert_invariant_broken(
        reynolds_number_kernel(&speed(1.0), &length(1.0), &nu(0.0)).unwrap_err(),
        "Re: nu = 0",
    );
    assert_invariant_broken(
        mach_number_kernel(&speed(1.0), &speed(0.0)).unwrap_err(),
        "Ma: a = 0",
    );
    assert_invariant_broken(
        weber_number_kernel(&density(1000.0), &speed(1.0), &length(1.0), 0.0).unwrap_err(),
        "We: sigma = 0",
    );
    assert_invariant_broken(
        prandtl_number_kernel(&nu(1e-5), 0.0).unwrap_err(),
        "Pr: alpha = 0",
    );
    assert_invariant_broken(
        peclet_number_kernel(&speed(1.0), &length(1.0), 0.0).unwrap_err(),
        "Pe: alpha = 0",
    );
    assert_invariant_broken(
        strouhal_number_kernel(1.0, &length(1.0), &speed(0.0)).unwrap_err(),
        "St: u = 0",
    );
    assert_invariant_broken(
        knudsen_number_kernel(1.0, &length(0.0)).unwrap_err(),
        "Kn: L = 0",
    );
    assert_invariant_broken(
        richardson_number_kernel(9.8, 1e-3, 1.0, &length(1.0), &speed(0.0)).unwrap_err(),
        "Ri: u = 0",
    );
    assert_invariant_broken(
        rayleigh_number_kernel(9.8, 1e-3, 1.0, &length(1.0), &nu(0.0), 1e-5).unwrap_err(),
        "Ra: nu = 0",
    );
    assert_invariant_broken(
        rayleigh_number_kernel(9.8, 1e-3, 1.0, &length(1.0), &nu(1e-5), 0.0).unwrap_err(),
        "Ra: alpha = 0",
    );
    assert_invariant_broken(
        grashof_number_kernel(9.8, 1e-3, 1.0, &length(1.0), &nu(0.0)).unwrap_err(),
        "Gr: nu = 0",
    );
    assert_invariant_broken(
        eckert_number_kernel(&speed(1.0), 0.0, 1.0).unwrap_err(),
        "Ec: cp = 0",
    );
    assert_invariant_broken(
        eckert_number_kernel(&speed(1.0), 1004.0, 0.0).unwrap_err(),
        "Ec: dT = 0",
    );
    assert_invariant_broken(
        schmidt_number_kernel(&nu(1e-5), 0.0).unwrap_err(),
        "Sc: D = 0",
    );
    assert_invariant_broken(lewis_number_kernel(1e-5, 0.0).unwrap_err(), "Le: D = 0");
    assert_invariant_broken(
        particle_stokes_number_kernel(1e-3, &speed(1.0), &length(0.0)).unwrap_err(),
        "St_p: L = 0",
    );
    assert_invariant_broken(
        capillary_number_kernel(&viscosity(1e-3), &speed(1.0), 0.0).unwrap_err(),
        "Ca: sigma = 0",
    );
    assert_invariant_broken(
        bond_number_kernel(&density(1000.0), 9.8, &length(1.0), 0.0).unwrap_err(),
        "Bo: sigma = 0",
    );
    assert_invariant_broken(
        nusselt_number_kernel(10.0, &length(1.0), 0.0).unwrap_err(),
        "Nu: k = 0",
    );
}

#[test]
fn test_froude_refuses_a_non_positive_g_times_l() {
    // Froude guards the product before the square root, because a negative radicand has no real
    // root. Zero gravity, zero length, and negative gravity are all refused.
    assert_invariant_broken(
        froude_number_kernel(&speed(1.0), 0.0, &length(1.0)).unwrap_err(),
        "Fr: g = 0",
    );
    assert_invariant_broken(
        froude_number_kernel(&speed(1.0), 9.80665, &length(0.0)).unwrap_err(),
        "Fr: L = 0",
    );
    assert_invariant_broken(
        froude_number_kernel(&speed(1.0), -9.80665, &length(1.0)).unwrap_err(),
        "Fr: g < 0",
    );
}

#[test]
fn test_the_refusals_survive_extreme_but_legal_magnitudes() {
    // A divisor that is merely tiny is not zero, and must not be refused: the guard is `== 0`, and
    // widening it to a tolerance would silently reject legitimate physics at small scales.
    assert!(reynolds_number_kernel(&speed(1.0), &length(1.0), &nu(f64::MIN_POSITIVE)).is_ok());
    assert!(knudsen_number_kernel(1.0, &length(f64::MIN_POSITIVE)).is_ok());
    assert!(nusselt_number_kernel(1.0, &length(1.0), f64::MIN_POSITIVE).is_ok());
}
