load("@crates//:defs.bzl", "aliases", "all_crate_deps", "lint_config")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_test_suite")

rust_library(
    name = "deep_causality_multivector",
    srcs = glob([
        "src/**/*.rs",
    ]),
    aliases = aliases(),
    crate_root = "src/lib.rs",
    lint_config = lint_config(),
    tags = [
        "data_structures",
    ],
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_doc(
    name = "doc",
    crate = ":deep_causality_multivector",
    tags = ["doc"],
    visibility = ["//visibility:public"],
)

rust_doc_test(
    name = "doc_test",
    crate = ":deep_causality_multivector",
    tags = ["doc-test"],
    visibility = ["//visibility:public"],
)

rust_test_suite(
    name = "errors",
    srcs = glob([
        "tests/errors/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_multivector",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "extensions",
    srcs = glob([
        "tests/extensions/hkt_multifield/*_tests.rs",
        "tests/extensions/hkt_multivector/*_tests.rs",
        "tests/extensions/iso_multifield/*_tests.rs",
        "tests/extensions/scalar_multivector/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_multivector",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "traits",
    srcs = glob([
        "tests/traits/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_multivector",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types/multifield",
    srcs = glob([
        "tests/types/multifield/*/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_multivector",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "types/multivector",
    srcs = glob([
        "tests/types/multivector/*/*_tests.rs",
        "tests/types/multivector/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_multivector",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test_suite(
    name = "alias",
    srcs = glob([
        "tests/alias/*_tests.rs",
    ]),
    tags = [
        "unit-test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # Crate to test
        ":deep_causality_multivector",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
