#SPDX-License-Identifier: MIT
#Copyright (c) "2023" . The DeepCausality Authors. All Rights Reserved.

name: Unused Deps

on: [ pull_request ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  unused_dependencies:
    name: cargo machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
      - uses: actions-rs/cargo@v1
        with:
          command: machete
          args:  deep_causality deep_causality_algorithms deep_causality_ast deep_causality_calculus deep_causality_core deep_causality_data_structures deep_causality_discovery deep_causality_ethos deep_causality_haft deep_causality_macros deep_causality_metric deep_causality_multivector deep_causality_num deep_causality_physics deep_causality_rand deep_causality_sparse deep_causality_tensor