# https://github.com/marketplace/actions/secret-scanner
name: Secret scanner
on:
  pull_request:
  push:
jobs:
  check-secrets:
    name: Checking for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: Secret Scanner
        uses: secret-scanner/action@0.2.1